/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-FRVNS on 2014-10-28 21:59:14,
 any modifications will be overwritten.
 ==============================================================
 */

package fr.factory.tif.hot;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import fr.factory.tif.res.ClassementGuide;
import fr.factory.tif.generic.confort.CategorieConfort;
import fr.factory.tif.generic.geographie.Pays;
import fr.factory.tif.pcu.parcjardin.ThemeParcJardin;
import fr.factory.tif.generic.acces.pointacces.PointAcces;
import fr.factory.tif.pcu.parcjardin.CategorieParcJardin;
import fr.factory.tif.generic.telecom.AccesTelecom;
import fr.factory.tif.vil.VillageVacance;
import fr.factory.tif.ascf.ActiviteSCF;
import fr.factory.tif.generic.tarifs.TypeTarifs;
import fr.factory.tif.org.SubTypeStructure;
import fr.factory.tif.hlo.labelclassement.Theme;
import java.util.Vector;
import fr.factory.tif.hlo.TypeHabitation;
import fr.factory.tif.iti.Itineraire;
import fr.factory.tif.vil.labelclassement.ClassementConfortSanitaire;
import fr.factory.tif.vil.animation.Disponibilite;
import fr.factory.tif.pcu.parcjardin.StyleParcJardin;
import fr.factory.tif.generic.personne.Civilite;
import fr.factory.tif.generic.equipement.Equipement;
import fr.factory.tif.generic.visite.Visite;
import fr.factory.tif.org.Organisme;
import fr.factory.tif.pcu.musee.Musee;
import fr.factory.tif.hlo.DescriptifHabitation;
import fr.factory.tif.generic.temps.Jour;
import java.io.Serializable;
import fr.factory.tif.pcu.sitemonument.SiteMonumentHistorique;
import fr.factory.tif.generic.geographie.Departement;
import fr.factory.tif.generic.service.TypeService;
import fr.factory.tif.generic.geographie.Region;
import fr.factory.tif.vil.SalleReunion;

import fr.factory.tif.application.Utilisateur;
import fr.factory.tif.ota.Prestation;
import fr.factory.tif.generic.labelclassement.Label;
import fr.factory.tif.vil.TypeClient;
import fr.factory.tif.generic.accueil.Accueil;
import fr.factory.tif.vil.Agrement;
import fr.factory.tif.generic.tarifs.Tarifs;
import fr.factory.tif.generic.utils.Langue;
import fr.factory.tif.generic.espace.Espace;
import fr.factory.tif.generic.geographie.Commune;
import fr.factory.tif.pcu.musee.ThemeMusee;
import fr.factory.tif.vil.animation.Animation;
import fr.factory.tif.generic.telecom.TypeTelecom;
import fr.factory.tif.pcu.sitemonument.CategorieSite;
import fr.factory.dao.interfaces.BifaceI18n;
import fr.factory.tif.vil.labelclassement.LabelClassement;
import fr.factory.tif.hlo.SubTypeHabitation;
import fr.factory.tif.iti.TypeThematique;
import fr.factory.tif.generic.tarifs.Charge;
import fr.factory.tif.pcu.PatrimoineCulturel;
import fr.factory.tif.pcu.musee.CategorieMusee;
import fr.factory.tif.generic.espace.TypeDescription;
import fr.factory.tif.generic.capacite.TypeCapacite;
import fr.factory.tif.generic.accueil.Horaire;
import fr.factory.tif.generic.temps.Saison;
import fr.factory.tif.pcu.sitemonument.ThemeSite;
import fr.factory.tif.generic.confort.Confort;
import fr.factory.tif.loi.Loisirs;
import fr.factory.tif.generic.reservation.TypeReservation;
import fr.factory.tif.hlo.HebergementLocatif;
import fr.factory.tif.generic.chaine.Chaine;
import fr.factory.tif.generic.service.Service;
import java.util.*;
import fr.factory.tif.hpa.HotelleriePleinAir;
import fr.factory.tif.generic.confort.TypeConfort;
import fr.factory.tif.deg.StatutExploitant;
import fr.factory.tif.generic.activite.Activite;
import fr.factory.tif.generic.visite.TypeVisite;
import fr.factory.tif.ota.Description;
import fr.factory.tif.generic.geographie.ZoneLocale;
import fr.factory.tif.generic.acces.localacces.TypeLocalAcces;
import fr.factory.tif.generic.labelclassement.Classement;
import java.util.Date;
import fr.factory.tif.generic.utils.Mesure;
import fr.factory.tif.res.DescriptionResto;
import fr.factory.tif.deg.VisiteDegustation;
import fr.factory.tif.pcu.parcjardin.ParcJardin;
import fr.factory.tif.generic.equipement.TypeEquipement;
import fr.factory.tif.generic.geographie.Microregion;
import java.util.Locale;
import fr.factory.tif.res.Specialite;
import fr.factory.tif.loi.TypeLoisirs;
import fr.factory.tif.generic.contact.TypeContact;
import fr.factory.tif.pcu.centre.CentreInterpretation;
import fr.factory.tif.generic.capacite.Capacite;
import java.lang.reflect.Method;
import fr.factory.tif.vil.labelclassement.ClassementEnvironement;
import fr.factory.tif.iti.Thematique;
import fr.factory.tif.vil.TypeGestion;
import fr.factory.tif.fma.ThemeFeteManifestation;
import fr.factory.tif.generic.geographie.Adresse;
import fr.factory.tif.generic.categorie.TypeCategorie;
import fr.factory.tif.generic.personne.Personne;
import fr.factory.tif.pcu.centre.ThemeCentreInterpretation;

import fr.factory.tif.mul.TypeMime;
import fr.factory.tif.generic.temps.PeriodeTemporelle;
import fr.factory.tif.vil.labelclassement.ClassementLoisirService;
import fr.factory.tif.ota.ObjetTouristiqueAbstrait;
import fr.factory.tif.pcu.sitemonument.StyleSite;
import fr.factory.tif.res.Restauration;
import java.util.HashMap;
import fr.factory.tif.generic.acces.localacces.LocalAcces;
import fr.factory.tif.ota.TypeObjetTouristique;
import fr.factory.tif.generic.activite.TypeActivite;
import fr.factory.tif.ascf.SportCultFormule;
import fr.factory.tif.fma.Evenement;
import fr.factory.tif.generic.tarifs.TypeCharge;
import fr.factory.tif.vil.animation.ThemeAnimation;
import fr.factory.tif.mul.TypeMultimedia;
import fr.factory.tif.vil.TypeHebergement;
import fr.factory.tif.generic.contact.Contact;
import fr.factory.tif.pna.PatrimoineNaturel;
import fr.factory.tif.vil.TypeBatiment;
import fr.factory.tif.generic.paiement.TypePaiement;
import fr.factory.tif.generic.reservation.Reservation;

import fr.factory.tif.fma.FeteManifestation;
import fr.factory.tif.generic.espace.TypeEspace;
import fr.factory.tif.generic.groupe.TypeGroupe;
import fr.factory.tif.generic.acces.pointacces.TypePointAcces;
import fr.factory.tif.generic.typeobjet.TypeObjet;
import fr.factory.tif.generic.accueil.OuvertureAccueil;
import fr.factory.dao.interfaces.Biface;
import fr.factory.tif.generic.groupe.Groupe;
import fr.factory.tif.vil.labelclassement.ClassementPrefectoral;
import fr.factory.tif.application.TypeUtilisateur;
import fr.factory.tif.ascf.TypeSportCultFormule;
import fr.factory.tif.generic.geographie.Canton;
import fr.factory.tif.generic.utils.TourHand;
import fr.factory.tif.mul.Multimedia;
import fr.factory.tif.generic.espace.DescriptionEspace;
import fr.factory.tif.ota.TypePrestation;
import fr.factory.tif.ascf.PrestationProposee;
import fr.factory.tif.deg.Degustation;
import fr.factory.tif.org.ClassementOTSI;

/**
 *  Hotellerie is specialized from ObjetTouristiqueAbstrait to
 * represent the objects of the type hotellerie (as hotel,...),
 * corresponding to the table HOT of the data model
 * 
 * @fdao.class table HOT
 * 
 * @fdao.subclass type fr.factory.tif.ota.ObjetTouristiqueAbstrait 
 * 
 * 
 * .
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Hotellerie
    extends ObjetTouristiqueAbstrait
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     *  Label of the Hotellerie, corresponding to the field LABEL
     * of the table
     * 
     * @fdao.property column LABEL
     * 
     *                  size 80
     * 
     * @tif.property  size 80
     * 
     * .
     */
    private String label;

    /**
     *  Will the hotelleie open 24/24?Corresponding to the field
     * OUV24 of the table
     * 
     * @fdao.property column OUV24
     * 
     *                  size 1
     * 
     * @tif.property  size 1
     * 
     * .
     */
    private boolean ouverture24 = false;

    /**
     *  Corresponding to the field VEILNUIT of the table
     * 
     * @fdao.property column VEILNUIT
     * 
     *                  size 1
     * 
     * @tif.property  size 1
     * 
     * .
     */
    private boolean veilleurNuit = false;

    /**
     *  Number of chamber classed, corresponding to the field
     * CHCLASS of the table
     * 
     * @fdao.property column CHCLASS
     * 
     *                  size 4
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private int nombreClassees = 0;

    /**
     *  Number of chamber with bath room, corresponding to the
     * field CHBAIN of the table.
     * 
     * @fdao.property column CHBAIN
     * 
     *                  size 4  
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private int nombreBains = 0;

    /**
     *  Number of chamber with shower, corresponding to the field
     * CHDOUCHE of the table
     * 
     * @fdao.property column CHDOUCHE
     * 
     *                  size 4 
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private int nombreDouches = 0;

    /**
     *  Number of no-smoking chamber, corresponding to the field
     * CHNONFUM of the table
     * 
     * @fdao.property column CHNONFUM
     * 
     *                  size 4
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private int nombreNonFum = 0;

    /**
     *  Number of Suites, corresponding to the field SUITES of the
     * table
     * 
     * @fdao.property column SUITES
     * 
     *                  size 4
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private int nombreSuites = 0;

    /**
     *  Number of chamber for people handicap., correspoding to the
     * field CHMOBRED of the table
     * 
     * @fdao.property column CHMOBRED
     * 
     *                  size 4
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private int nombrerMobReduite = 0;

    /**
     *  Number of studios, corresponding to the field STUDIOS of
     * the table
     * 
     * @fdao.property column STUDIOS
     * 
     *                   size 4
     * 
     * @tif.property   size 4
     * 
     * .
     */
    private int nombreStudios = 0;

    /**
     *  Number of appartements, corresponding to the field APPART
     * of the table
     * 
     * @fdao.property column APPART
     * 
     *                   size 4
     * 
     * @tif.property   size 4
     * 
     * .
     */
    private int nombreAppartements = 0;

    /**
     *  Number of meeting rooms, corresponding to the field
     * SALLREUN of the table
     * 
     * @fdao.property column SALLREUN
     * 
     *                  size 4
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private int nombreReunions = 0;

    /**
     * 
     * 
     *  Est-ce que le produit est un adherent syndicat?
     * 
     * @fdao.property column ADHERENTSYN
     * 
     *                 size 1
     * 
     * @tif.property  size 1
     * 
     * .
     */
    private boolean adherentSyndicat = false;

    /**
     *  Description about meeting rooms, corresponding to the field
     * DESCSALLE of the table
     * 
     * @fdao.property column DESCSALLE
     * 
     *                  i18n true
     * 
     *                  size 80
     * 
     * @tif.property  size 80
     * 
     * .
     */
    private String[] descriptionSalleReunion;

    /**
     * 
     * 
     *  Classement of the Restauration
     * 
     * @fdao.component class
     * fr.factory.tif.generic.labelclassement.LabelClassement
     * 
     *  				   table HOT1_LABELCLAS
     * 
     * .
     */
    private Vector labelClassement;

    /**
     * @fdao.component class fr.factory.tif.generic.confort.Confort
     * 
     *                   table OTA_CONFORT
     * 
     * .
     */
    private Vector confort;

    /**
     * @fdao.component class
     * fr.factory.tif.generic.activite.Activite
     * 
     *                   table OTA_ACTIVITE
     * 
     * .
     */
    private Vector activite;

    /**
     * @fdao.component class fr.factory.tif.generic.service.Service
     * 
     *                   table OTA_SERVICE
     * 
     * .
     */
    private Vector service;

    /**
     * @fdao.component class
     * fr.factory.tif.generic.equipement.Equipement
     * 
     *                   table OTA_EQUIP
     * 
     * .
     */
    private Vector equipement;

    /**
     * @fdao.component class fr.factory.tif.generic.chaine.Chaine
     * 
     *                   table OTA_CHAINE
     * 
     * .
     */
    private Vector chaine;

    /**
     *  
     * 
     * @fdao.component class
     * fr.factory.tif.generic.typeobjet.TypeObjet
     * 
     * .
     */
    private TypeObjet typeObjet;

    /**
     * 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.categorie.TypeCategorie
     * 
     * .
     */
    private TypeCategorie categorie;

      public Vector getActivite() {
  /* {null=Vector
}*/

		return activite;
  }

      public String getLabel() {
  /* {null=String
}*/

		return label;
  }

      public int getNombreAppartements() {
  /* {null=int
}*/

		return nombreAppartements;
  }

      public int getNombreBains() {
  /* {null=int
}*/

		return nombreBains;
  }

      public int getNombreClassees() {
  /* {null=int
}*/

		return nombreClassees;
  }

      public int getNombreDouches() {
  /* {null=int
}*/

		return nombreDouches;
  }

      public int getNombreNonFum() {
  /* {null=int
}*/

		return nombreNonFum;
  }

      public int getNombreReunions() {
  /* {null=int
}*/

		return nombreReunions;
  }

      public int getNombrerMobReduite() {
  /* {null=int
}*/

		return nombrerMobReduite;
  }

      public int getNombreStudios() {
  /* {null=int
}*/

		return nombreStudios;
  }

      public int getNombreSuites() {
  /* {null=int
}*/

		return nombreSuites;
  }

      public boolean isOuverture24() {
  /* {null=boolean
}*/

		return ouverture24;
  }

      public TypeObjet getTypeObjet() {
  /* {null=TypeObjet
}*/

		return typeObjet;
  }

      public boolean isVeilleurNuit() {
  /* {null=boolean
}*/

		return veilleurNuit;
  }

      public void setActivite(Vector vector) {
  /* {null=void
}*/

		activite= vector;
  }

      public void setLabel(String string) {
  /* {null=void
}*/

		label= string;
  }

      public void setNombreAppartements(int i) {
  /* {null=void
}*/

		nombreAppartements= i;
  }

      public void setNombreBains(int i) {
  /* {null=void
}*/

		nombreBains= i;
  }

      public void setNombreClassees(int i) {
  /* {null=void
}*/

		nombreClassees= i;
  }

      public void setNombreDouches(int i) {
  /* {null=void
}*/

		nombreDouches= i;
  }

      public void setNombreNonFum(int i) {
  /* {null=void
}*/

		nombreNonFum= i;
  }

      public void setNombreReunions(int i) {
  /* {null=void
}*/

		nombreReunions= i;
  }

      public void setNombrerMobReduite(int i) {
  /* {null=void
}*/

		nombrerMobReduite= i;
  }

      public void setNombreStudios(int i) {
  /* {null=void
}*/

		nombreStudios= i;
  }

      public void setNombreSuites(int i) {
  /* {null=void
}*/

		nombreSuites= i;
  }

      public void setOuverture24(boolean b) {
  /* {null=void
}*/

		ouverture24= b;
  }

      public void setTypeObjet(TypeObjet objet) {
  /* {null=void
}*/

		typeObjet= objet;
  }

      public void setVeilleurNuit(boolean b) {
  /* {null=void
}*/

		veilleurNuit= b;
  }

      public String[] getDescriptionSalleReunion() {
  /* {null=String[]
}*/

		return descriptionSalleReunion;
  }

      public void setDescriptionSalleReunion(String[] strings) {
  /* {null=void
}*/

		descriptionSalleReunion= strings;
  }

      public Vector getChaine() {
		return chaine;
  }

      public Vector getConfort() {
		return confort;
  }

      public Vector getEquipement() {
		return equipement;
  }

      public Vector getService() {
		return service;
  }

      public void setChaine(Vector vector) {
  /* {param=vector
}*/

		chaine = vector;
  }

      public void setConfort(Vector vector) {
  /* {param=vector
}*/

		confort = vector;
  }

      public void setEquipement(Vector vector) {
  /* {param=vector
}*/

		equipement = vector;
  }

      public void setService(Vector vector) {
  /* {param=vector
}*/

		service = vector;
  }

      public boolean isAdherentSyndicat() {
  /* {return

	=* @return boolean
}*/

		return adherentSyndicat;
  }

      public void setAdherentSyndicat(boolean b) {
  /* {param=b

, null=void
}*/

		adherentSyndicat = b;
  }

      public TypeCategorie getCategorie() {
  /* {return

	=* @return TypeCategorie
}*/

		return categorie;
  }

      public void setCategorie(TypeCategorie categorie) {
  /* {param=categorie

, null=void
}*/

		this.categorie = categorie;
  }

      public Vector getLabelClassement() {
  /* {return

	=* @return Vector
}*/

		return labelClassement;
  }

      public void setLabelClassement(Vector vector) {
  /* {param=vector

, null=void
}*/

		labelClassement = vector;
  }

}
