/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-FRVNS on 2014-10-28 21:59:14,
 any modifications will be overwritten.
 ==============================================================
 */

package fr.factory.tif.res;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import fr.factory.tif.generic.confort.CategorieConfort;
import fr.factory.tif.generic.geographie.Pays;
import fr.factory.tif.pcu.parcjardin.ThemeParcJardin;
import fr.factory.tif.generic.acces.pointacces.PointAcces;
import fr.factory.tif.pcu.parcjardin.CategorieParcJardin;
import fr.factory.tif.generic.telecom.AccesTelecom;
import fr.factory.tif.vil.VillageVacance;
import fr.factory.tif.ascf.ActiviteSCF;
import fr.factory.tif.generic.tarifs.TypeTarifs;
import fr.factory.tif.org.SubTypeStructure;
import fr.factory.tif.hlo.labelclassement.Theme;
import java.util.Vector;
import fr.factory.tif.hlo.TypeHabitation;
import fr.factory.tif.iti.Itineraire;
import fr.factory.tif.vil.labelclassement.ClassementConfortSanitaire;
import fr.factory.tif.vil.animation.Disponibilite;
import fr.factory.tif.pcu.parcjardin.StyleParcJardin;
import fr.factory.tif.generic.personne.Civilite;
import fr.factory.tif.generic.equipement.Equipement;
import fr.factory.tif.generic.visite.Visite;
import fr.factory.tif.org.Organisme;
import fr.factory.tif.pcu.musee.Musee;
import fr.factory.tif.hlo.DescriptifHabitation;
import fr.factory.tif.generic.temps.Jour;
import java.io.Serializable;
import fr.factory.tif.pcu.sitemonument.SiteMonumentHistorique;
import fr.factory.tif.generic.geographie.Departement;
import fr.factory.tif.generic.service.TypeService;
import fr.factory.tif.generic.geographie.Region;
import fr.factory.tif.vil.SalleReunion;

import fr.factory.tif.application.Utilisateur;
import fr.factory.tif.ota.Prestation;
import fr.factory.tif.generic.labelclassement.Label;
import fr.factory.tif.vil.TypeClient;
import fr.factory.tif.generic.accueil.Accueil;
import fr.factory.tif.vil.Agrement;
import fr.factory.tif.generic.tarifs.Tarifs;
import fr.factory.tif.generic.utils.Langue;
import fr.factory.tif.generic.espace.Espace;
import fr.factory.tif.generic.geographie.Commune;
import fr.factory.tif.pcu.musee.ThemeMusee;
import fr.factory.tif.vil.animation.Animation;
import fr.factory.tif.generic.telecom.TypeTelecom;
import fr.factory.tif.pcu.sitemonument.CategorieSite;
import fr.factory.dao.interfaces.BifaceI18n;
import fr.factory.tif.vil.labelclassement.LabelClassement;
import fr.factory.tif.hlo.SubTypeHabitation;
import fr.factory.tif.iti.TypeThematique;
import fr.factory.tif.generic.tarifs.Charge;
import fr.factory.tif.pcu.PatrimoineCulturel;
import fr.factory.tif.pcu.musee.CategorieMusee;
import fr.factory.tif.generic.espace.TypeDescription;
import fr.factory.tif.generic.capacite.TypeCapacite;
import fr.factory.tif.generic.accueil.Horaire;
import fr.factory.tif.generic.temps.Saison;
import fr.factory.tif.pcu.sitemonument.ThemeSite;
import fr.factory.tif.generic.confort.Confort;
import fr.factory.tif.loi.Loisirs;
import fr.factory.tif.generic.reservation.TypeReservation;
import fr.factory.tif.hlo.HebergementLocatif;
import fr.factory.tif.generic.chaine.Chaine;
import fr.factory.tif.generic.service.Service;
import java.util.*;
import fr.factory.tif.hpa.HotelleriePleinAir;
import fr.factory.tif.generic.confort.TypeConfort;
import fr.factory.tif.deg.StatutExploitant;
import fr.factory.tif.generic.activite.Activite;
import fr.factory.tif.generic.visite.TypeVisite;
import fr.factory.tif.ota.Description;
import fr.factory.tif.generic.geographie.ZoneLocale;
import fr.factory.tif.generic.acces.localacces.TypeLocalAcces;
import fr.factory.tif.generic.labelclassement.Classement;
import java.util.Date;
import fr.factory.tif.generic.utils.Mesure;
import fr.factory.tif.deg.VisiteDegustation;
import fr.factory.tif.pcu.parcjardin.ParcJardin;
import fr.factory.tif.generic.equipement.TypeEquipement;
import fr.factory.tif.generic.geographie.Microregion;
import java.util.Locale;
import fr.factory.tif.loi.TypeLoisirs;
import fr.factory.tif.generic.contact.TypeContact;
import fr.factory.tif.pcu.centre.CentreInterpretation;
import fr.factory.tif.generic.capacite.Capacite;
import java.lang.reflect.Method;
import fr.factory.tif.vil.labelclassement.ClassementEnvironement;
import fr.factory.tif.iti.Thematique;
import fr.factory.tif.vil.TypeGestion;
import fr.factory.tif.fma.ThemeFeteManifestation;
import fr.factory.tif.generic.geographie.Adresse;
import fr.factory.tif.generic.categorie.TypeCategorie;
import fr.factory.tif.generic.personne.Personne;
import fr.factory.tif.pcu.centre.ThemeCentreInterpretation;

import fr.factory.tif.mul.TypeMime;
import fr.factory.tif.generic.temps.PeriodeTemporelle;
import fr.factory.tif.vil.labelclassement.ClassementLoisirService;
import fr.factory.tif.ota.ObjetTouristiqueAbstrait;
import fr.factory.tif.pcu.sitemonument.StyleSite;
import java.util.HashMap;
import fr.factory.tif.generic.acces.localacces.LocalAcces;
import fr.factory.tif.ota.TypeObjetTouristique;
import fr.factory.tif.generic.activite.TypeActivite;
import fr.factory.tif.ascf.SportCultFormule;
import fr.factory.tif.fma.Evenement;
import fr.factory.tif.generic.tarifs.TypeCharge;
import fr.factory.tif.vil.animation.ThemeAnimation;
import fr.factory.tif.mul.TypeMultimedia;
import fr.factory.tif.vil.TypeHebergement;
import fr.factory.tif.generic.contact.Contact;
import fr.factory.tif.pna.PatrimoineNaturel;
import fr.factory.tif.vil.TypeBatiment;
import fr.factory.tif.generic.paiement.TypePaiement;
import fr.factory.tif.generic.reservation.Reservation;

import fr.factory.tif.fma.FeteManifestation;
import fr.factory.tif.generic.espace.TypeEspace;
import fr.factory.tif.generic.groupe.TypeGroupe;
import fr.factory.tif.generic.acces.pointacces.TypePointAcces;
import fr.factory.tif.generic.typeobjet.TypeObjet;
import fr.factory.tif.generic.accueil.OuvertureAccueil;
import fr.factory.dao.interfaces.Biface;
import fr.factory.tif.generic.groupe.Groupe;
import fr.factory.tif.vil.labelclassement.ClassementPrefectoral;
import fr.factory.tif.application.TypeUtilisateur;
import fr.factory.tif.ascf.TypeSportCultFormule;
import fr.factory.tif.generic.geographie.Canton;
import fr.factory.tif.generic.utils.TourHand;
import fr.factory.tif.mul.Multimedia;
import fr.factory.tif.generic.espace.DescriptionEspace;
import fr.factory.tif.hot.Hotellerie;
import fr.factory.tif.ota.TypePrestation;
import fr.factory.tif.ascf.PrestationProposee;
import fr.factory.tif.deg.Degustation;
import fr.factory.tif.org.ClassementOTSI;

/**
 * 
 * 
 * @author viet
 * 
 *  Entity who represent the type Restauration of TIF v.2.2
 * 
 * @fdao.class table RES
 * 
 * @fdao.subclass type fr.factory.tif.ota.ObjetTouristiqueAbstrait 
 * 
 * 
 * .
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Restauration
    extends ObjetTouristiqueAbstrait
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * 
     * 
     *  Name of the Chef of the Restauration
     * 
     * @fdao.property column NOM_CHEF
     * 
     *                 size 80
     * 
     * @tif.property  size 80
     * 
     * .
     */
    private String nomChef;

    /**
     * 
     * 
     *  Labels of the Restauration
     * 
     * @fdao.property column LABEL
     * 
     *                 size 80
     * 
     * @tif.property  size 80
     * 
     * .
     */
    private String label;

    /**
     * 
     * 
     *  Number of rooms in the Restauration
     * 
     * @fdao.property column NBSALL
     * 
     *                 size 2
     * 
     * @tif.property  size 2
     * 
     * .
     */
    private long nombreSalles = 0L;

    /**
     * 
     * 
     *  Number of room with air-conditioner in the Restauration
     * 
     * @fdao.property column NBCLIM
     * 
     *                 size 2
     * 
     * @tif.property  size 2
     * 
     * .
     */
    private long nombreClims = 0L;

    /**
     * 
     * 
     *  Maximum number of rooms with Couvert in the Restauration
     * 
     * @fdao.property column NBCOUV
     * 
     *                 size 4 
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private long nombreMaxCouverts = 0L;

    /**
     * 
     * 
     *  Number of Couvert en Terrasse in the Restauration
     * 
     * @fdao.property column NBCOUVTER
     * 
     *                 size 3
     * 
     * @tif.property  size 3
     * 
     * .
     */
    private long nombreCouvertTerrasses = 0L;

    /**
     * 
     * 
     *  Number of the halls in the Restauration
     * 
     * @fdao.property column NBREUN
     * 
     *                 size 3
     * 
     * @tif.property  size 3
     * 
     * .
     */
    private long nombreSalleReunions = 0L;

    /**
     * 
     * 
     *  
     * 
     * @fdao.property column ADHERENTSYN
     * 
     *                 size 1
     * 
     * @tif.property  size 1
     * 
     * .
     */
    private boolean adherentSyndicat = false;

    /**
     * 
     * 
     *  Capacity of the Restauration
     * .
     */
    private Capacite capacite;

    /**
     * 
     * 
     *  Cuisine Etrangere of the Restauration
     * 
     * @fdao.component class 
     * fr.factory.tif.generic.geographie.Pays
     * 
     *  				   table RES1_ETR
     * 
     * .
     */
    private Vector cuisineEtrangere;

    /**
     * 
     * 
     *  Specialites of the Restauration
     * 
     * @fdao.component class fr.factory.tif.res.Specialite
     * 
     *   			   table RES1_CUL
     * 
     * .
     */
    private Vector specialite;

    /**
     * 
     * 
     *  Classement Guide of the Restauration
     * 
     * @fdao.component class fr.factory.tif.res.ClassementGuide
     * 
     *                  table RES1_GUI 
     * 
     * .
     */
    private Vector classementGuide;

    /**
     * 
     * 
     *  Classement of the Restauration
     * 
     * @fdao.component class
     * fr.factory.tif.generic.labelclassement.LabelClassement
     * 
     *  				   table RES1_LABELCLAS
     * 
     * .
     */
    private Vector labelClassement;

    /**
     * 
     * 
     *  Description of rooms of the Restauration
     * 
     * @fdao.component class fr.factory.tif.res.DescriptionResto
     * 
     * .
     */
    private DescriptionResto descriptionResto;

    /**
     * 
     * 
     *  Subtype of the Restauration
     * 
     * @fdao.component class
     * fr.factory.tif.generic.typeobjet.TypeObjet
     * 
     * .
     */
    private TypeObjet typeObjet;

    /**
     * 
     * 
     *  Collection of categories of the Restauration
     * 
     * @fdao.component class
     * fr.factory.tif.generic.categorie.TypeCategorie
     * 
     *                  table RES1_CAT
     * 
     * .
     */
    private Vector categorie;

    /**
     * 
     * 
     *  Equipements of the Restauration
     * 
     * @fdao.component class
     * fr.factory.tif.generic.equipement.Equipement
     * 
     *                  table OTA_EQUIP
     * 
     * .
     */
    private Vector equipement;

    /**
     * 
     * 
     *  Servives of the Restauration
     * 
     * @fdao.component class fr.factory.tif.generic.service.Service
     * 
     *                  table OTA_SERVICE
     * 
     * .
     */
    private Vector service;

    /**
     * 
     * 
     *  Activite of the Restauration
     * 
     * @fdao.component class
     * fr.factory.tif.generic.activite.Activite
     * 
     *                  table OTA_ACTIVITE
     * 
     * .
     */
    private Vector activite;

    /**
     * 
     * 
     *  Chaine of the Restauration
     * 
     * @fdao.component class fr.factory.tif.generic.chaine.Chaine 
     * 
     *                  table OTA_CHAINE
     * 
     * .
     */
    private Vector chaine;

      public Vector getClassementGuide() {
		return classementGuide;
  }

      public Vector getCuisineEtrangere() {
		return cuisineEtrangere;
  }

      public DescriptionResto getDescriptionResto() {
		return descriptionResto;
  }

      public Vector getSpecialite() {
		return specialite;
  }

      public void setClassementGuide(Vector vector) {
  /* {param=vector
}*/

		classementGuide = vector;
  }

      public void setCuisineEtrangere(Vector vector) {
  /* {param=vector
}*/

		cuisineEtrangere = vector;
  }

      public void setDescriptionResto(DescriptionResto resto) {
  /* {param=resto
}*/

		descriptionResto = resto;
  }

      public void setSpecialite(Vector vector) {
  /* {param=vector
}*/

		specialite = vector;
  }

      public String getLabel() {
		return label;
  }

      public long getNombreClims() {
		return nombreClims;
  }

      public long getNombreCouvertTerrasses() {
		return nombreCouvertTerrasses;
  }

      public long getNombreMaxCouverts() {
		return nombreMaxCouverts;
  }

      public long getNombreSalleReunions() {
		return nombreSalleReunions;
  }

      public long getNombreSalles() {
		return nombreSalles;
  }

      public String getNomChef() {
		return nomChef;
  }

      public void setLabel(String string) {
  /* {param=string
}*/

		label = string;
  }

      public void setNombreClims(long l) {
  /* {param=l
}*/

		nombreClims = l;
  }

      public void setNombreCouvertTerrasses(long l) {
  /* {param=l
}*/

		nombreCouvertTerrasses = l;
  }

      public void setNombreMaxCouverts(long l) {
  /* {param=l
}*/

		nombreMaxCouverts = l;
  }

      public void setNombreSalleReunions(long l) {
  /* {param=l
}*/

		nombreSalleReunions = l;
  }

      public void setNombreSalles(long l) {
  /* {param=l
}*/

		nombreSalles = l;
  }

      public void setNomChef(String string) {
  /* {param=string
}*/

		nomChef = string;
  }

      public TypeObjet getTypeObjet() {
		return typeObjet;
  }

      public void setTypeObjet(TypeObjet objet) {
  /* {param=objet
}*/

		typeObjet = objet;
  }

      public Vector getActivite() {
		return activite;
  }

      public Vector getChaine() {
		return chaine;
  }

      public Vector getEquipement() {
		return equipement;
  }

      public Vector getService() {
		return service;
  }

      public void setActivite(Vector vector) {
  /* {param=vector
}*/

		activite = vector;
  }

      public void setChaine(Vector vector) {
  /* {param=vector
}*/

		chaine = vector;
  }

      public void setEquipement(Vector vector) {
  /* {param=vector
}*/

		equipement = vector;
  }

      public void setService(Vector vector) {
  /* {param=vector
}*/

		service = vector;
  }

      public boolean isAdherentSyndicat() {
  /* {return

	=* @return boolean
}*/

		return adherentSyndicat;
  }

      public void setAdherentSyndicat(boolean b) {
  /* {param=b

, null=void
}*/

		adherentSyndicat = b;
  }

      public Vector getCategorie() {
  /* {return

	=* @return Vector
}*/

		return categorie;
  }

      public void setCategorie(Vector vector) {
  /* {param=vector

, null=void
}*/

		categorie = vector;
  }

      public Vector getLabelClassement() {
  /* {return

	=* @return Vector
}*/

		return labelClassement;
  }

      public void setLabelClassement(Vector vector) {
  /* {param=vector

, null=void
}*/

		labelClassement = vector;
  }

      public Capacite getCapacite() {
  /* {return

	=* @return Capacite
}*/

		return capacite;
  }

      public void setCapacite(Capacite capacite) {
  /* {param=capacite

, null=void
}*/

		this.capacite = capacite;
  }

}
