/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-FRVNS on 2014-10-28 21:59:14,
 any modifications will be overwritten.
 ==============================================================
 */

package fr.factory.tif.ota;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import fr.factory.tif.res.ClassementGuide;
import fr.factory.tif.generic.confort.CategorieConfort;
import fr.factory.tif.generic.geographie.Pays;
import fr.factory.tif.pcu.parcjardin.ThemeParcJardin;
import fr.factory.tif.generic.acces.pointacces.PointAcces;
import fr.factory.tif.pcu.parcjardin.CategorieParcJardin;
import fr.factory.tif.generic.telecom.AccesTelecom;
import fr.factory.tif.vil.VillageVacance;
import fr.factory.tif.ascf.ActiviteSCF;
import fr.factory.tif.generic.tarifs.TypeTarifs;
import fr.factory.tif.org.SubTypeStructure;
import fr.factory.tif.hlo.labelclassement.Theme;
import java.util.Vector;
import fr.factory.tif.hlo.TypeHabitation;
import fr.factory.tif.iti.Itineraire;
import fr.factory.tif.vil.labelclassement.ClassementConfortSanitaire;
import fr.factory.tif.vil.animation.Disponibilite;
import fr.factory.tif.pcu.parcjardin.StyleParcJardin;
import fr.factory.tif.generic.personne.Civilite;
import fr.factory.tif.generic.equipement.Equipement;
import fr.factory.tif.generic.visite.Visite;
import fr.factory.tif.org.Organisme;
import fr.factory.tif.pcu.musee.Musee;
import fr.factory.tif.hlo.DescriptifHabitation;
import fr.factory.tif.generic.temps.Jour;
import java.io.Serializable;
import fr.factory.tif.pcu.sitemonument.SiteMonumentHistorique;
import fr.factory.tif.generic.geographie.Departement;
import fr.factory.tif.generic.service.TypeService;
import fr.factory.tif.generic.geographie.Region;
import fr.factory.tif.vil.SalleReunion;

import fr.factory.tif.application.Utilisateur;
import fr.factory.tif.generic.labelclassement.Label;
import fr.factory.tif.vil.TypeClient;
import fr.factory.tif.generic.accueil.Accueil;
import fr.factory.tif.vil.Agrement;
import fr.factory.tif.generic.tarifs.Tarifs;
import fr.factory.tif.generic.utils.Langue;
import fr.factory.tif.generic.espace.Espace;
import fr.factory.tif.generic.geographie.Commune;
import fr.factory.tif.pcu.musee.ThemeMusee;
import fr.factory.tif.vil.animation.Animation;
import fr.factory.tif.generic.telecom.TypeTelecom;
import fr.factory.tif.pcu.sitemonument.CategorieSite;
import fr.factory.dao.interfaces.BifaceI18n;
import fr.factory.tif.vil.labelclassement.LabelClassement;
import fr.factory.tif.hlo.SubTypeHabitation;
import fr.factory.tif.iti.TypeThematique;
import fr.factory.tif.generic.tarifs.Charge;
import fr.factory.tif.pcu.PatrimoineCulturel;
import fr.factory.tif.pcu.musee.CategorieMusee;
import fr.factory.tif.generic.espace.TypeDescription;
import fr.factory.tif.generic.capacite.TypeCapacite;
import fr.factory.tif.generic.accueil.Horaire;
import fr.factory.tif.generic.temps.Saison;
import fr.factory.tif.pcu.sitemonument.ThemeSite;
import fr.factory.tif.generic.confort.Confort;
import fr.factory.tif.loi.Loisirs;
import fr.factory.tif.generic.reservation.TypeReservation;
import fr.factory.tif.hlo.HebergementLocatif;
import fr.factory.tif.generic.chaine.Chaine;
import fr.factory.tif.generic.service.Service;
import java.util.*;
import fr.factory.tif.hpa.HotelleriePleinAir;
import fr.factory.tif.generic.confort.TypeConfort;
import fr.factory.tif.deg.StatutExploitant;
import fr.factory.tif.generic.activite.Activite;
import fr.factory.tif.generic.visite.TypeVisite;
import fr.factory.tif.generic.geographie.ZoneLocale;
import fr.factory.tif.generic.acces.localacces.TypeLocalAcces;
import fr.factory.tif.generic.labelclassement.Classement;
import java.util.Date;
import fr.factory.tif.generic.utils.Mesure;
import fr.factory.tif.res.DescriptionResto;
import fr.factory.tif.deg.VisiteDegustation;
import fr.factory.tif.pcu.parcjardin.ParcJardin;
import fr.factory.tif.generic.equipement.TypeEquipement;
import fr.factory.tif.generic.geographie.Microregion;
import java.util.Locale;
import fr.factory.tif.res.Specialite;
import fr.factory.tif.loi.TypeLoisirs;
import fr.factory.tif.generic.contact.TypeContact;
import fr.factory.tif.pcu.centre.CentreInterpretation;
import fr.factory.tif.generic.capacite.Capacite;
import java.lang.reflect.Method;
import fr.factory.tif.vil.labelclassement.ClassementEnvironement;
import fr.factory.tif.iti.Thematique;
import fr.factory.tif.vil.TypeGestion;
import fr.factory.tif.fma.ThemeFeteManifestation;
import fr.factory.tif.generic.geographie.Adresse;
import fr.factory.tif.generic.categorie.TypeCategorie;
import fr.factory.tif.generic.personne.Personne;
import fr.factory.tif.pcu.centre.ThemeCentreInterpretation;

import fr.factory.tif.mul.TypeMime;
import fr.factory.tif.generic.temps.PeriodeTemporelle;
import fr.factory.tif.vil.labelclassement.ClassementLoisirService;
import fr.factory.tif.pcu.sitemonument.StyleSite;
import fr.factory.tif.res.Restauration;
import java.util.HashMap;
import fr.factory.tif.generic.acces.localacces.LocalAcces;
import fr.factory.tif.generic.activite.TypeActivite;
import fr.factory.tif.ascf.SportCultFormule;
import fr.factory.tif.fma.Evenement;
import fr.factory.tif.generic.tarifs.TypeCharge;
import fr.factory.tif.vil.animation.ThemeAnimation;
import fr.factory.tif.mul.TypeMultimedia;
import fr.factory.tif.vil.TypeHebergement;
import fr.factory.tif.generic.contact.Contact;
import fr.factory.tif.pna.PatrimoineNaturel;
import fr.factory.tif.vil.TypeBatiment;
import fr.factory.tif.generic.paiement.TypePaiement;
import fr.factory.tif.generic.reservation.Reservation;

import fr.factory.tif.fma.FeteManifestation;
import fr.factory.tif.generic.espace.TypeEspace;
import fr.factory.tif.generic.groupe.TypeGroupe;
import fr.factory.tif.generic.acces.pointacces.TypePointAcces;
import fr.factory.tif.generic.typeobjet.TypeObjet;
import fr.factory.tif.generic.accueil.OuvertureAccueil;
import fr.factory.dao.interfaces.Biface;
import fr.factory.tif.generic.groupe.Groupe;
import fr.factory.tif.vil.labelclassement.ClassementPrefectoral;
import fr.factory.tif.application.TypeUtilisateur;
import fr.factory.tif.ascf.TypeSportCultFormule;
import fr.factory.tif.generic.geographie.Canton;
import fr.factory.tif.generic.utils.TourHand;
import fr.factory.tif.mul.Multimedia;
import fr.factory.tif.generic.espace.DescriptionEspace;
import fr.factory.tif.hot.Hotellerie;
import fr.factory.tif.ascf.PrestationProposee;
import fr.factory.tif.deg.Degustation;
import fr.factory.tif.org.ClassementOTSI;

/**
 *  ObjetTouristiqueAbstrait represent an abstrait tourist object ,
 * contains all common informations about tourist object
 * 
 * @fdao.class table OTA
 * 
 * .
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class ObjetTouristiqueAbstrait
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     *  Internal ID of Objet Touristique, corresponding to field
     * ID_OBJ of the table OTA
     * 
     * @fdao.id column ID_OBJ
     * 
     *            size   20
     * 
     * .
     */
    private Long id;

    /**
     * 
     * 
     *  Name of the Objet Touristique
     * 
     * @fdao.property column NOM
     * 
     *                 size 80
     * 
     * @tif.property  size 80
     * 
     * .
     */
    private String nom;

    /**
     * 
     * 
     *  Raison sociale
     * 
     * @fdao.property column SOCIETE
     * 
     *                 size 160
     * 
     * @tif.property  size 160
     * 
     * .
     */
    private String raisonSociale;

    /**
     * 
     * 
     *  Sigle
     * 
     * @fdao.property column SIGLE
     * 
     *                 size 10
     * 
     * @tif.property  size 10
     * 
     * .
     */
    private String sigle;

    /**
     *  
     * 
     *  ID of Objet in TourinFrance format, corresponding to field
     * ID of the table OTA.
     * 
     * @fdao.property column ID
     * 
     *                 size 16
     * 
     * @tif.property  size 16
     * 
     * .
     */
    private String idTourinFrance;

    /**
     *  Date of creation of Object, corresponding to field DATECREA
     * of the table OTA
     * 
     * @fdao.property column DATECREA
     * 
     * .
     */
    private java.util.Date dateCreation;

    /**
     *  
     * 
     *  Update date of Object, corresponding to field DATEMAJ of
     * the table OTA
     * 
     * @fdao.property column DATEMAJ
     * 
     * .
     */
    private java.util.Date dateMiseAJour;

    /**
     *  
     * 
     *  Legal Infors of Object, corresponding to field SIRET of the
     * table OTA
     * 
     * @fdao.property column SIRET
     * 
     *                 size 14
     * 
     * @tif.property  size 14
     * 
     * .
     */
    private String siret;

    /**
     *  Legal Infors of Object, corresponding to field APE of the
     * table OTA
     * 
     * @fdao.property column APE
     * 
     *                  size 4
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private String ape;

    /**
     * 
     * 
     *  Legal Infors of Object, corresponding to field RCS of the
     * table OTA
     * 
     * @fdao.property column RCS
     * 
     *                 size 12
     * 
     * @tif.property  size 12
     * 
     * .
     */
    private String rcs;

    /**
     * 
     * 
     * @fdao.property column CODE_CARTE
     * 
     *                 size 11
     * 
     * @tif.property  size 11
     * 
     * .
     */
    private String codeCarte;

    /**
     * 
     * 
     *  Property :
     * 
     * @fdao.property column LONGITUDE
     * 
     *                 size 10
     * 
     * @tif.property  size 10
     * 
     * .
     */
    private String longitude;

    /**
     * 
     * 
     *  Property :
     * 
     * @fdao.property column LATITUDE
     * 
     *                 size 10 
     * 
     * @tif.property  size 10
     * 
     * .
     */
    private String latitude;

    /**
     * 
     * 
     *  Property :
     * 
     * @fdao.property column ALTITUDE
     * 
     *                 size 4 
     * 
     * @tif.property  size 4
     * 
     * .
     */
    private long altitude = 0L;

    /**
     *  
     * 
     *  Identification additional informations of Object,
     * corresponding to field IDCOMPL of the table OTA
     * 
     * @fdao.property column IDCOMPL
     * 
     *                  i18n  true
     * 
     *                  size 80
     * 
     * @tif.property  size 80 
     * 
     * .
     */
    private String[] identificationComplement;

    /**
     * 
     * 
     *  Property :
     * 
     * @fdao.component class
     * fr.factory.tif.generic.geographie.Adresse
     * 
     * .
     */
    private Adresse adresse;

    /**
     * 
     * 
     * @fdao.component class
     * fr.factory.tif.ota.TypeObjetTouristique
     * 
     * .
     */
    private TypeObjetTouristique typeObjetTouristique;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.generic.accueil.Accueil
     * 
     * .
     */
    private Accueil accueil;

    /**
     * 
     * 
     *  
     * 
     * @fdao.component class
     * fr.factory.tif.generic.acces.pointacces.PointAcces
     * 
     * 				  table OTA2_POINT
     * 
     * 				
     * 
     * .
     */
    private Vector pointAcces;

    /**
     * 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.acces.localacces.LocalAcces
     * 
     *  				  table OTA2_ZONE
     * 
     * @element-type LocalAcces
     * 
     * .
     */
    private Vector localAcces;

    /**
     * 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.telecom.AccesTelecom
     * 
     *                  table OTA1_COMM
     * 
     * @element-type   AccesTelecom
     * 
     * .
     */
    private Vector accesTelecom;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.generic.contact.Contact
     * 
     *                  table OTA1_CONT
     * 
     * @element-type  Contact
     * 
     * .
     */
    private Vector contact;

    /**
     * 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.paiement.TypePaiement
     * 
     *                  table OTA5_MODE
     * 
     * @element-type   TypePaiement
     * 
     * .
     */
    private Vector typePaiement;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.ota.Description
     * 
     * @element-type Description
     * 
     * .
     */
    private Description description;

    /**
     * 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.reservation.Reservation
     * 
     *                  table OTA3_RESA
     * 
     * @element-type   Reservation
     * 
     * .
     */
    private Vector reservation;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.ota.Prestation
     * 
     * @element-type Prestations
     * 
     * .
     */
    private Vector prestations;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.generic.espace.Espace
     * 
     *                  table OTA_ESPACE
     * 
     * @element-type Espace
     * 
     * .
     */
    private Vector espace;

    /**
     * @fdao.component class fr.factory.tif.generic.tarifs.Tarifs
     * 
     *                   table OTA_TARIFS
     * 
     * @element-type Tarifs
     * 
     * .
     */
    private Vector tarifs;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method breakDescriptionAssociation.
     * 
     * @param description
     */
    public void breakDescriptionAssociation( Description description )
    {
        if ( this.description != description )
        {
            throw new IllegalStateException( "description isn't associated." );
        }

        this.description = null;
    } //-- void breakDescriptionAssociation( Description )

    /**
     * Method createDescriptionAssociation.
     * 
     * @param description
     */
    public void createDescriptionAssociation( Description description )
    {
        if ( this.description != null )
        {
            breakDescriptionAssociation( this.description );
        }

        this.description = description;
    } //-- void createDescriptionAssociation( Description )

      public Vector getAccesTelecom() {
  /* {null=Vector
}*/

		return accesTelecom;
  }

      public String getApe() {
  /* {null=String
}*/

		return ape;
  }

      public Vector getContact() {
  /* {null=Vector
}*/

		return contact;
  }

      public Date getDateCreation() {
  /* {null=Date
}*/

		return dateCreation;
  }

      public Date getDateMiseAJour() {
  /* {null=Date
}*/

		return dateMiseAJour;
  }

      public Description getDescription() {
  /* {null=Description
}*/

		return description;
  }

      public Vector getEspace() {
  /* {null=Vector
}*/

		return espace;
  }

      public Long getId() {
  /* {null=Long
}*/

		return id;
  }

      public Vector getLocalAcces() {
  /* {null=Vector
}*/

		return localAcces;
  }

      public Vector getPointAcces() {
  /* {null=Vector
}*/

		return pointAcces;
  }

      public String getRcs() {
  /* {null=String
}*/

		return rcs;
  }

      public Vector getReservation() {
  /* {null=Vector
}*/

		return reservation;
  }

      public String getSiret() {
  /* {null=String
}*/

		return siret;
  }

      public void setAccesTelecom(Vector vector) {
  /* {null=void
}*/

		accesTelecom= vector;
  }

      public void setApe(String string) {
  /* {null=void
}*/

		ape= string;
  }

      public void setContact(Vector vector) {
  /* {null=void
}*/

		contact= vector;
  }

      public void setDateCreation(Date date) {
  /* {null=void
}*/

		dateCreation= date;
  }

      public void setDateMiseAJour(Date date) {
  /* {null=void
}*/

		dateMiseAJour= date;
  }

      public void setDescription(Description description) {
  /* {null=void
}*/

		this.description= description;
  }

      public void setEspace(Vector vector) {
  /* {null=void
}*/

		espace= vector;
  }

      public void setId(Long long1) {
  /* {null=void
}*/

		id= long1;
  }

      public void setLocalAcces(Vector vector) {
  /* {null=void
}*/

		localAcces= vector;
  }

      public void setPointAcces(Vector vector) {
  /* {null=void
}*/

		pointAcces= vector;
  }

      public void setRcs(String string) {
  /* {null=void
}*/

		rcs= string;
  }

      public void setReservation(Vector vector) {
  /* {null=void
}*/

		reservation= vector;
  }

      public void setSiret(String string) {
  /* {null=void
}*/

		siret= string;
  }

      public String getRaisonSociale() {
  /* {null=String
}*/

		return raisonSociale;
  }

      public String getSigle() {
  /* {null=String
}*/

		return sigle;
  }

      public void setRaisonSociale(String string) {
  /* {null=void
}*/

		raisonSociale= string;
  }

      public void setSigle(String string) {
  /* {null=void
}*/

		sigle= string;
  }

      public Vector getPrestations() {
  /* {null=Vector
}*/

		return prestations;
  }

      public TypeObjetTouristique getTypeObjetTouristique() {
  /* {null=TypeObjetTouristique
}*/

		return typeObjetTouristique;
  }

      public Vector getTypePaiement() {
  /* {null=Vector
}*/

		return typePaiement;
  }

      public void setPrestations(Vector vector) {
  /* {null=void
}*/

		prestations= vector;
  }

      public void setTypeObjetTouristique(TypeObjetTouristique touristique) {
  /* {null=void
}*/

		typeObjetTouristique= touristique;
  }

      public void setTypePaiement(Vector vector) {
  /* {null=void
}*/

		typePaiement= vector;
  }

      public String[] getIdentificationComplement() {
		return identificationComplement;
  }

      public void setIdentificationComplement(String[] strings) {
  /* {param=strings
}*/

		identificationComplement = strings;
  }

      public Vector getTarifs() {
  /* {return

	=* @return Vector
}*/

		return tarifs;
  }

      public void setTarifs(Vector vector) {
  /* {param=vector

, null=void
}*/

		tarifs = vector;
  }

      public String getLatitude() {
  /* {return

	=* @return String
}*/

		return latitude;
  }

      public String getLongitude() {
  /* {return

	=* @return String
}*/

		return longitude;
  }

      public void setLatitude(String string) {
  /* {param=string

, null=void
}*/

		latitude = string;
  }

      public void setLongitude(String string) {
  /* {param=string

, null=void
}*/

		longitude = string;
  }

      public Adresse getAdresse() {
  /* {return

	=* @return Adresse
}*/

		return adresse;
  }

      public void setAdresse(Adresse adresse) {
  /* {param=adresse

, null=void
}*/

		this.adresse = adresse;
  }

      public String getNom() {
  /* {return

	=* @return String
}*/

		return nom;
  }

      public void setNom(String string) {
  /* {param=string

, null=void
}*/

		nom = string;
  }

      public Accueil getAccueil() {
  /* {return

	=* @return Accueil
}*/

		return accueil;
  }

      public void setAccueil(Accueil accueil) {
  /* {param=accueil

, null=void
}*/

		this.accueil = accueil;
  }

      public String getCodeCarte() {
  /* {return

	=* @return String
}*/

		return codeCarte;
  }

      public void setCodeCarte(String string) {
  /* {param=string

, null=void
}*/

		codeCarte = string;
  }

      public long getAltitude() {
		return altitude;
  }

      public void setAltitude(long l) {
  /* {param=l
}*/

		altitude = l;
  }

      public String getIdTourinFrance() {
		return idTourinFrance;
  }

      public void setIdTourinFrance(String string) {
  /* {param=string
}*/

		idTourinFrance = string;
  }

}
