/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-FRVNS on 2014-10-28 21:59:14,
 any modifications will be overwritten.
 ==============================================================
 */

package fr.factory.tif.generic.espace;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import fr.factory.tif.res.ClassementGuide;
import fr.factory.tif.generic.confort.CategorieConfort;
import fr.factory.tif.generic.geographie.Pays;
import fr.factory.tif.pcu.parcjardin.ThemeParcJardin;
import fr.factory.tif.generic.acces.pointacces.PointAcces;
import fr.factory.tif.pcu.parcjardin.CategorieParcJardin;
import fr.factory.tif.generic.telecom.AccesTelecom;
import fr.factory.tif.vil.VillageVacance;
import fr.factory.tif.ascf.ActiviteSCF;
import fr.factory.tif.generic.tarifs.TypeTarifs;
import fr.factory.tif.org.SubTypeStructure;
import fr.factory.tif.hlo.labelclassement.Theme;
import java.util.Vector;
import fr.factory.tif.hlo.TypeHabitation;
import fr.factory.tif.iti.Itineraire;
import fr.factory.tif.vil.labelclassement.ClassementConfortSanitaire;
import fr.factory.tif.vil.animation.Disponibilite;
import fr.factory.tif.pcu.parcjardin.StyleParcJardin;
import fr.factory.tif.generic.personne.Civilite;
import fr.factory.tif.generic.equipement.Equipement;
import fr.factory.tif.generic.visite.Visite;
import fr.factory.tif.org.Organisme;
import fr.factory.tif.pcu.musee.Musee;
import fr.factory.tif.hlo.DescriptifHabitation;
import fr.factory.tif.generic.temps.Jour;
import java.io.Serializable;
import fr.factory.tif.pcu.sitemonument.SiteMonumentHistorique;
import fr.factory.tif.generic.geographie.Departement;
import fr.factory.tif.generic.service.TypeService;
import fr.factory.tif.generic.geographie.Region;
import fr.factory.tif.vil.SalleReunion;

import fr.factory.tif.application.Utilisateur;
import fr.factory.tif.ota.Prestation;
import fr.factory.tif.generic.labelclassement.Label;
import fr.factory.tif.vil.TypeClient;
import fr.factory.tif.generic.accueil.Accueil;
import fr.factory.tif.vil.Agrement;
import fr.factory.tif.generic.tarifs.Tarifs;
import fr.factory.tif.generic.utils.Langue;
import fr.factory.tif.generic.geographie.Commune;
import fr.factory.tif.pcu.musee.ThemeMusee;
import fr.factory.tif.vil.animation.Animation;
import fr.factory.tif.generic.telecom.TypeTelecom;
import fr.factory.tif.pcu.sitemonument.CategorieSite;
import fr.factory.dao.interfaces.BifaceI18n;
import fr.factory.tif.vil.labelclassement.LabelClassement;
import fr.factory.tif.hlo.SubTypeHabitation;
import fr.factory.tif.iti.TypeThematique;
import fr.factory.tif.generic.tarifs.Charge;
import fr.factory.tif.pcu.PatrimoineCulturel;
import fr.factory.tif.pcu.musee.CategorieMusee;
import fr.factory.tif.generic.capacite.TypeCapacite;
import fr.factory.tif.generic.accueil.Horaire;
import fr.factory.tif.generic.temps.Saison;
import fr.factory.tif.pcu.sitemonument.ThemeSite;
import fr.factory.tif.generic.confort.Confort;
import fr.factory.tif.loi.Loisirs;
import fr.factory.tif.generic.reservation.TypeReservation;
import fr.factory.tif.hlo.HebergementLocatif;
import fr.factory.tif.generic.chaine.Chaine;
import fr.factory.tif.generic.service.Service;
import java.util.*;
import fr.factory.tif.hpa.HotelleriePleinAir;
import fr.factory.tif.generic.confort.TypeConfort;
import fr.factory.tif.deg.StatutExploitant;
import fr.factory.tif.generic.activite.Activite;
import fr.factory.tif.generic.visite.TypeVisite;
import fr.factory.tif.ota.Description;
import fr.factory.tif.generic.geographie.ZoneLocale;
import fr.factory.tif.generic.acces.localacces.TypeLocalAcces;
import fr.factory.tif.generic.labelclassement.Classement;
import java.util.Date;
import fr.factory.tif.generic.utils.Mesure;
import fr.factory.tif.res.DescriptionResto;
import fr.factory.tif.deg.VisiteDegustation;
import fr.factory.tif.pcu.parcjardin.ParcJardin;
import fr.factory.tif.generic.equipement.TypeEquipement;
import fr.factory.tif.generic.geographie.Microregion;
import java.util.Locale;
import fr.factory.tif.res.Specialite;
import fr.factory.tif.loi.TypeLoisirs;
import fr.factory.tif.generic.contact.TypeContact;
import fr.factory.tif.pcu.centre.CentreInterpretation;
import fr.factory.tif.generic.capacite.Capacite;
import java.lang.reflect.Method;
import fr.factory.tif.vil.labelclassement.ClassementEnvironement;
import fr.factory.tif.iti.Thematique;
import fr.factory.tif.vil.TypeGestion;
import fr.factory.tif.fma.ThemeFeteManifestation;
import fr.factory.tif.generic.geographie.Adresse;
import fr.factory.tif.generic.categorie.TypeCategorie;
import fr.factory.tif.generic.personne.Personne;
import fr.factory.tif.pcu.centre.ThemeCentreInterpretation;

import fr.factory.tif.mul.TypeMime;
import fr.factory.tif.generic.temps.PeriodeTemporelle;
import fr.factory.tif.vil.labelclassement.ClassementLoisirService;
import fr.factory.tif.ota.ObjetTouristiqueAbstrait;
import fr.factory.tif.pcu.sitemonument.StyleSite;
import fr.factory.tif.res.Restauration;
import java.util.HashMap;
import fr.factory.tif.generic.acces.localacces.LocalAcces;
import fr.factory.tif.ota.TypeObjetTouristique;
import fr.factory.tif.generic.activite.TypeActivite;
import fr.factory.tif.ascf.SportCultFormule;
import fr.factory.tif.fma.Evenement;
import fr.factory.tif.generic.tarifs.TypeCharge;
import fr.factory.tif.vil.animation.ThemeAnimation;
import fr.factory.tif.mul.TypeMultimedia;
import fr.factory.tif.vil.TypeHebergement;
import fr.factory.tif.generic.contact.Contact;
import fr.factory.tif.pna.PatrimoineNaturel;
import fr.factory.tif.vil.TypeBatiment;
import fr.factory.tif.generic.paiement.TypePaiement;
import fr.factory.tif.generic.reservation.Reservation;

import fr.factory.tif.fma.FeteManifestation;
import fr.factory.tif.generic.groupe.TypeGroupe;
import fr.factory.tif.generic.acces.pointacces.TypePointAcces;
import fr.factory.tif.generic.typeobjet.TypeObjet;
import fr.factory.tif.generic.accueil.OuvertureAccueil;
import fr.factory.dao.interfaces.Biface;
import fr.factory.tif.generic.groupe.Groupe;
import fr.factory.tif.vil.labelclassement.ClassementPrefectoral;
import fr.factory.tif.application.TypeUtilisateur;
import fr.factory.tif.ascf.TypeSportCultFormule;
import fr.factory.tif.generic.geographie.Canton;
import fr.factory.tif.generic.utils.TourHand;
import fr.factory.tif.mul.Multimedia;
import fr.factory.tif.hot.Hotellerie;
import fr.factory.tif.ota.TypePrestation;
import fr.factory.tif.ascf.PrestationProposee;
import fr.factory.tif.deg.Degustation;
import fr.factory.tif.org.ClassementOTSI;

/**
 *  
 * 
 *   Espace
 * 
 * @fdao.class table ESPACE
 * 
 * .
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Espace
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     *  
     * 
     *   ID of the Espace
     * 
     * @fdao.id column ID_ESPACE
     * 
     * .
     */
    private Long id;

    /**
     *  
     * 
     * @fdao.property column NOM_ESPACE
     * 
     *                  size 160 
     * 
     * .
     */
    private String nom;

    /**
     *  
     * 
     * @fdao.property column ACCES_HANDI_ESPACE
     * 
     * .
     */
    private boolean accesHandicape = false;

    /**
     *  
     * 
     * @fdao.property column SURF_ESPACE
     * 
     * .
     */
    private long surface = 0L;

    /**
     *  
     * 
     * @fdao.property column PRIV_ESPACE
     * 
     * .
     */
    private boolean prive = false;

    /**
     *  
     * 
     * @fdao.property column NONFUM_ESPACE
     * 
     * .
     */
    private boolean nonFumeur = false;

    /**
     *  
     * 
     * @fdao.property column ANX_ESPACE
     * 
     * .
     */
    private boolean annex = false;

    /**
     *  
     * 
     * @fdao.property column PROP_ESPACE
     * 
     * .
     */
    private boolean proprietaire = false;

    /**
     *  
     * 
     * @fdao.property column ADV_ESPACE
     * 
     * .
     */
    private boolean adv = false;

    /**
     * 
     * 
     * @fdao.property column RESERVE
     * 
     *                 size 1
     * 
     * .
     */
    private boolean espacePrivatisable = false;

    /**
     * 
     * 
     * @fdao.property column SERV_INCLU
     * 
     *                 size 1
     * 
     * .
     */
    private boolean servicePrivatisableInclus = false;

    /**
     * 
     * 
     * @fdao.property column COMPL_PRIVA
     * 
     *                  i18n   true
     * 
     *                  size   160
     * 
     * .
     */
    private String[] complementPrivatisable;

    /**
     *  
     * 
     *   Type of the Espace
     * 
     * @fdao.component class
     * fr.factory.tif.generic.espace.TypeEspace
     * 
     * .
     */
    private TypeEspace typeEspace;

    /**
     *  
     * 
     *   Description of the Espace
     * 
     * @fdao.component class
     * fr.factory.tif.generic.espace.DescriptionEspace
     * 
     *                   table DESCRIPTION_ESPACE
     * 
     * .
     */
    private Vector descriptionEspace;

    /**
     * 
     * 
     *  Capacite of the Espace
     * 
     * @fdao.component class
     * fr.factory.tif.generic.capacite.Capacite
     * 
     *                  table ESPACE_CAPACITE
     * 
     * .
     */
    private Vector capacite;

      public boolean isAccesHandicape() {
  /* {null=boolean 
}*/

		return accesHandicape;
  }

      public boolean isAdv() {
  /* {null=boolean 
}*/

		return adv;
  }

      public boolean isAnnex() {
  /* {null=boolean 
}*/

		return annex;
  }

      public Vector getDescriptionEspace() {
  /* {null=Vector
}*/

		return descriptionEspace;
  }

      public Long getId() {
  /* {null=Long
}*/

		return id;
  }

      public String getNom() {
  /* {null=String
}*/

		return nom;
  }

      public boolean isNonFumeur() {
  /* {null=boolean 
}*/

		return nonFumeur;
  }

      public boolean isPrive() {
  /* {null=boolean 
}*/

		return prive;
  }

      public TypeEspace getTypeEspace() {
  /* {null=TypeEspace
}*/

		return typeEspace;
  }

      public void setDescriptionEspace(Vector vector) {
  /* {null=void
}*/

		descriptionEspace= vector;
  }

      public void setId(Long long1) {
  /* {null=void
}*/

		id= long1;
  }

      public void setNom(String string) {
  /* {null=void
}*/

		nom= string;
  }

      public void setTypeEspace(TypeEspace espace) {
  /* {null=void
}*/

		typeEspace= espace;
  }

      public boolean isProprietaire() {
		return proprietaire;
  }

      public long getSurface() {
		return surface;
  }

      public void setAccesHandicape(boolean b) {
  /* {param=b
}*/

		accesHandicape = b;
  }

      public void setAdv(boolean b) {
  /* {param=b
}*/

		adv = b;
  }

      public void setAnnex(boolean b) {
  /* {param=b
}*/

		annex = b;
  }

      public void setNonFumeur(boolean b) {
  /* {param=b
}*/

		nonFumeur = b;
  }

      public void setPrive(boolean b) {
  /* {param=b
}*/

		prive = b;
  }

      public void setProprietaire(boolean b) {
  /* {param=b
}*/

		proprietaire = b;
  }

      public void setSurface(long l) {
  /* {param=l
}*/

		surface = l;
  }

      public Vector getCapacite() {
		return capacite;
  }

      public void setCapacite(Vector vector) {
  /* {param=vector
}*/

		capacite = vector;
  }

      public String[] getComplementPrivatisable() {
  /* {return

	=* @return String[]
}*/

		return complementPrivatisable;
  }

      public boolean isEspacePrivatisable() {
  /* {return

	=* @return boolean
}*/

		return espacePrivatisable;
  }

      public boolean isServicePrivatisableInclus() {
  /* {return

	=* @return boolean
}*/

		return servicePrivatisableInclus;
  }

      public void setComplementPrivatisable(String[] strings) {
  /* {param=strings

, null=void
}*/

		complementPrivatisable = strings;
  }

      public void setEspacePrivatisable(boolean b) {
  /* {param=b

, null=void
}*/

		espacePrivatisable = b;
  }

      public void setServicePrivatisableInclus(boolean b) {
  /* {param=b

, null=void
}*/

		servicePrivatisableInclus = b;
  }

}
