/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-FRVNS on 2014-10-28 21:59:14,
 any modifications will be overwritten.
 ==============================================================
 */

package fr.factory.tif.generic.tarifs;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import fr.factory.tif.res.ClassementGuide;
import fr.factory.tif.generic.confort.CategorieConfort;
import fr.factory.tif.generic.geographie.Pays;
import fr.factory.tif.pcu.parcjardin.ThemeParcJardin;
import fr.factory.tif.generic.acces.pointacces.PointAcces;
import fr.factory.tif.pcu.parcjardin.CategorieParcJardin;
import fr.factory.tif.generic.telecom.AccesTelecom;
import fr.factory.tif.vil.VillageVacance;
import fr.factory.tif.ascf.ActiviteSCF;
import fr.factory.tif.org.SubTypeStructure;
import fr.factory.tif.hlo.labelclassement.Theme;
import java.util.Vector;
import fr.factory.tif.hlo.TypeHabitation;
import fr.factory.tif.iti.Itineraire;
import fr.factory.tif.vil.labelclassement.ClassementConfortSanitaire;
import fr.factory.tif.vil.animation.Disponibilite;
import fr.factory.tif.pcu.parcjardin.StyleParcJardin;
import fr.factory.tif.generic.personne.Civilite;
import fr.factory.tif.generic.equipement.Equipement;
import fr.factory.tif.generic.visite.Visite;
import fr.factory.tif.org.Organisme;
import fr.factory.tif.pcu.musee.Musee;
import fr.factory.tif.hlo.DescriptifHabitation;
import fr.factory.tif.generic.temps.Jour;
import java.io.Serializable;
import fr.factory.tif.pcu.sitemonument.SiteMonumentHistorique;
import fr.factory.tif.generic.geographie.Departement;
import fr.factory.tif.generic.service.TypeService;
import fr.factory.tif.generic.geographie.Region;
import fr.factory.tif.vil.SalleReunion;

import fr.factory.tif.application.Utilisateur;
import fr.factory.tif.ota.Prestation;
import fr.factory.tif.generic.labelclassement.Label;
import fr.factory.tif.vil.TypeClient;
import fr.factory.tif.generic.accueil.Accueil;
import fr.factory.tif.vil.Agrement;
import fr.factory.tif.generic.utils.Langue;
import fr.factory.tif.generic.espace.Espace;
import fr.factory.tif.generic.geographie.Commune;
import fr.factory.tif.pcu.musee.ThemeMusee;
import fr.factory.tif.vil.animation.Animation;
import fr.factory.tif.generic.telecom.TypeTelecom;
import fr.factory.tif.pcu.sitemonument.CategorieSite;
import fr.factory.dao.interfaces.BifaceI18n;
import fr.factory.tif.vil.labelclassement.LabelClassement;
import fr.factory.tif.hlo.SubTypeHabitation;
import fr.factory.tif.iti.TypeThematique;
import fr.factory.tif.pcu.PatrimoineCulturel;
import fr.factory.tif.pcu.musee.CategorieMusee;
import fr.factory.tif.generic.espace.TypeDescription;
import fr.factory.tif.generic.capacite.TypeCapacite;
import fr.factory.tif.generic.accueil.Horaire;
import fr.factory.tif.generic.temps.Saison;
import fr.factory.tif.pcu.sitemonument.ThemeSite;
import fr.factory.tif.generic.confort.Confort;
import fr.factory.tif.loi.Loisirs;
import fr.factory.tif.generic.reservation.TypeReservation;
import fr.factory.tif.hlo.HebergementLocatif;
import fr.factory.tif.generic.chaine.Chaine;
import fr.factory.tif.generic.service.Service;
import java.util.*;
import fr.factory.tif.hpa.HotelleriePleinAir;
import fr.factory.tif.generic.confort.TypeConfort;
import fr.factory.tif.deg.StatutExploitant;
import fr.factory.tif.generic.activite.Activite;
import fr.factory.tif.generic.visite.TypeVisite;
import fr.factory.tif.ota.Description;
import fr.factory.tif.generic.geographie.ZoneLocale;
import fr.factory.tif.generic.acces.localacces.TypeLocalAcces;
import fr.factory.tif.generic.labelclassement.Classement;
import java.util.Date;
import fr.factory.tif.generic.utils.Mesure;
import fr.factory.tif.res.DescriptionResto;
import fr.factory.tif.deg.VisiteDegustation;
import fr.factory.tif.pcu.parcjardin.ParcJardin;
import fr.factory.tif.generic.equipement.TypeEquipement;
import fr.factory.tif.generic.geographie.Microregion;
import java.util.Locale;
import fr.factory.tif.res.Specialite;
import fr.factory.tif.loi.TypeLoisirs;
import fr.factory.tif.generic.contact.TypeContact;
import fr.factory.tif.pcu.centre.CentreInterpretation;
import fr.factory.tif.generic.capacite.Capacite;
import java.lang.reflect.Method;
import fr.factory.tif.vil.labelclassement.ClassementEnvironement;
import fr.factory.tif.iti.Thematique;
import fr.factory.tif.vil.TypeGestion;
import fr.factory.tif.fma.ThemeFeteManifestation;
import fr.factory.tif.generic.geographie.Adresse;
import fr.factory.tif.generic.categorie.TypeCategorie;
import fr.factory.tif.generic.personne.Personne;
import fr.factory.tif.pcu.centre.ThemeCentreInterpretation;

import fr.factory.tif.mul.TypeMime;
import fr.factory.tif.generic.temps.PeriodeTemporelle;
import fr.factory.tif.vil.labelclassement.ClassementLoisirService;
import fr.factory.tif.ota.ObjetTouristiqueAbstrait;
import fr.factory.tif.pcu.sitemonument.StyleSite;
import fr.factory.tif.res.Restauration;
import java.util.HashMap;
import fr.factory.tif.generic.acces.localacces.LocalAcces;
import fr.factory.tif.ota.TypeObjetTouristique;
import fr.factory.tif.generic.activite.TypeActivite;
import fr.factory.tif.ascf.SportCultFormule;
import fr.factory.tif.fma.Evenement;
import fr.factory.tif.vil.animation.ThemeAnimation;
import fr.factory.tif.mul.TypeMultimedia;
import fr.factory.tif.vil.TypeHebergement;
import fr.factory.tif.generic.contact.Contact;
import fr.factory.tif.pna.PatrimoineNaturel;
import fr.factory.tif.vil.TypeBatiment;
import fr.factory.tif.generic.paiement.TypePaiement;
import fr.factory.tif.generic.reservation.Reservation;

import fr.factory.tif.fma.FeteManifestation;
import fr.factory.tif.generic.espace.TypeEspace;
import fr.factory.tif.generic.groupe.TypeGroupe;
import fr.factory.tif.generic.acces.pointacces.TypePointAcces;
import fr.factory.tif.generic.typeobjet.TypeObjet;
import fr.factory.tif.generic.accueil.OuvertureAccueil;
import fr.factory.dao.interfaces.Biface;
import fr.factory.tif.generic.groupe.Groupe;
import fr.factory.tif.vil.labelclassement.ClassementPrefectoral;
import fr.factory.tif.application.TypeUtilisateur;
import fr.factory.tif.ascf.TypeSportCultFormule;
import fr.factory.tif.generic.geographie.Canton;
import fr.factory.tif.generic.utils.TourHand;
import fr.factory.tif.mul.Multimedia;
import fr.factory.tif.generic.espace.DescriptionEspace;
import fr.factory.tif.hot.Hotellerie;
import fr.factory.tif.ota.TypePrestation;
import fr.factory.tif.ascf.PrestationProposee;
import fr.factory.tif.deg.Degustation;
import fr.factory.tif.org.ClassementOTSI;

/**
 *  Tarifs define a type Tarif all touriste object 
 * 
 * @fdao.class table TARIFS
 * 
 * .
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Tarifs
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     *  
     * 
     *  Object's internal ID
     * 
     * @fdao.id column ID_TARIFS
     * 
     * .
     */
    private Long id;

    /**
     *  Minimum tarif (Euro)
     * 
     * @fdao.property column MINI_EURO_TARIFS
     * 
     *                  size 12
     * 
     *                  scale 2
     * 
     * @tif.property  size 8
     * 
     *                  scale 2
     * 
     * .
     */
    private float minimumEuro = 0.0f;

    /**
     *  Maximum tarif (Euro)
     * 
     * @fdao.property column MAXI_EURO_TARIFS
     * 
     *                  size 12
     * 
     *                  scale 2
     * 
     * @tif.property  size 8
     * 
     *                  scale 2
     * 
     * .
     */
    private float maximumEuro = 0.0f;

    /**
     *  Maximum age for reduction
     * 
     * @fdao.property column AGE_MAXI_TARIFS
     * 
     *                  size 3
     * 
     * @tif.property  size 3
     * 
     * .
     */
    private int ageMaxi = 0;

    /**
     * 
     * 
     * @fdao.property column CHARGES_TARIFS
     * 
     * .
     */
    private boolean chargesComprises = false;

    /**
     * 
     * 
     * @fdao.property column DEB_TARIFS
     * 
     * .
     */
    private java.util.Date dateDebut;

    /**
     * 
     * 
     * @fdao.property column FIN_TARIFS
     * 
     * .
     */
    private java.util.Date dateFin;

    /**
     * 
     * 
     * @fdao.property column ANN_TARIFS
     * 
     * .
     */
    private java.util.Date anneeReference;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.generic.tarifs.Charge
     * 
     *                  table TARIFS_CHARGES
     * 
     * .
     */
    private Vector charge;

    /**
     *  Complement informations for tarifs
     * 
     * @fdao.property column COMPLEMENT_TARIFS
     * 
     *                  i18n true
     * 
     *                  size 80
     * 
     * @tif.property  size 80
     * 
     * .
     */
    private String[] complementTarifs;

    /**
     *  
     * 
     * @fdao.component class
     * fr.factory.tif.generic.tarifs.TypeTarifs
     * 
     * .
     */
    private TypeTarifs typeTarifs;

    /**
     *  
     * 
     * @fdao.component class fr.factory.tif.generic.temps.Saison
     * 
     * .
     */
    private Saison saison;

      public int getAgeMaxi() {
  /* {null=int
}*/

		return ageMaxi;
  }

      public Long getId() {
  /* {null=Long
}*/

		return id;
  }

      public float getMaximumEuro() {
  /* {null=int
}*/

		return maximumEuro;
  }

      public float getMinimumEuro() {
  /* {null=int
}*/

		return minimumEuro;
  }

      public TypeTarifs getTypeTarifs() {
  /* {null=TypeTarifs
}*/

		return typeTarifs;
  }

      public void setAgeMaxi(int i) {
  /* {null=void
}*/

		ageMaxi= i;
  }

      public void setId(Long long1) {
  /* {null=void
}*/

		id= long1;
  }

      public void setMaximumEuro(float i) {
  /* {null=void
}*/

		maximumEuro= i;
  }

      public void setMinimumEuro(float i) {
  /* {null=void
}*/

		minimumEuro= i;
  }

      public void setTypeTarifs(TypeTarifs tarifs) {
  /* {null=void
}*/

		typeTarifs= tarifs;
  }

      public Saison getSaison() {
  /* {null=Saison
}*/

		return saison;
  }

      public void setSaison(Saison saison) {
  /* {null=void
}*/

		this.saison= saison;
  }

      public String[] getComplementTarifs() {
		return complementTarifs;
  }

      public void setComplementTarifs(String[] strings) {
  /* {param=strings
}*/

		complementTarifs = strings;
  }

      public Date getAnneeReference() {
  /* {return

	=* @return Date
}*/

		return anneeReference;
  }

      public Vector getCharge() {
  /* {return

	=* @return Vector
}*/

		return charge;
  }

      public boolean isChargesComprises() {
  /* {return

	=* @return boolean
}*/

		return chargesComprises;
  }

      public Date getDateDebut() {
  /* {return

	=* @return Date
}*/

		return dateDebut;
  }

      public Date getDateFin() {
  /* {return

	=* @return Date
}*/

		return dateFin;
  }

      public void setAnneeReference(Date date) {
  /* {param=date

, null=void
}*/

		anneeReference = date;
  }

      public void setCharge(Vector vector) {
  /* {param=vector

, null=void
}*/

		charge = vector;
  }

      public void setChargesComprises(boolean b) {
  /* {param=b

, null=void
}*/

		chargesComprises = b;
  }

      public void setDateDebut(Date date) {
  /* {param=date

, null=void
}*/

		dateDebut = date;
  }

      public void setDateFin(Date date) {
  /* {param=date

, null=void
}*/

		dateFin = date;
  }

}
