/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-FRVNS on 2014-10-28 21:59:14,
 any modifications will be overwritten.
 ==============================================================
 */

package fr.factory.tif.generic.accueil;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import fr.factory.tif.res.ClassementGuide;
import fr.factory.tif.generic.confort.CategorieConfort;
import fr.factory.tif.generic.geographie.Pays;
import fr.factory.tif.pcu.parcjardin.ThemeParcJardin;
import fr.factory.tif.generic.acces.pointacces.PointAcces;
import fr.factory.tif.pcu.parcjardin.CategorieParcJardin;
import fr.factory.tif.generic.telecom.AccesTelecom;
import fr.factory.tif.vil.VillageVacance;
import fr.factory.tif.ascf.ActiviteSCF;
import fr.factory.tif.generic.tarifs.TypeTarifs;
import fr.factory.tif.org.SubTypeStructure;
import fr.factory.tif.hlo.labelclassement.Theme;
import java.util.Vector;
import fr.factory.tif.hlo.TypeHabitation;
import fr.factory.tif.iti.Itineraire;
import fr.factory.tif.vil.labelclassement.ClassementConfortSanitaire;
import fr.factory.tif.vil.animation.Disponibilite;
import fr.factory.tif.pcu.parcjardin.StyleParcJardin;
import fr.factory.tif.generic.personne.Civilite;
import fr.factory.tif.generic.equipement.Equipement;
import fr.factory.tif.generic.visite.Visite;
import fr.factory.tif.org.Organisme;
import fr.factory.tif.pcu.musee.Musee;
import fr.factory.tif.hlo.DescriptifHabitation;
import fr.factory.tif.generic.temps.Jour;
import java.io.Serializable;
import fr.factory.tif.pcu.sitemonument.SiteMonumentHistorique;
import fr.factory.tif.generic.geographie.Departement;
import fr.factory.tif.generic.service.TypeService;
import fr.factory.tif.generic.geographie.Region;
import fr.factory.tif.vil.SalleReunion;

import fr.factory.tif.application.Utilisateur;
import fr.factory.tif.ota.Prestation;
import fr.factory.tif.generic.labelclassement.Label;
import fr.factory.tif.vil.TypeClient;
import fr.factory.tif.vil.Agrement;
import fr.factory.tif.generic.tarifs.Tarifs;
import fr.factory.tif.generic.utils.Langue;
import fr.factory.tif.generic.espace.Espace;
import fr.factory.tif.generic.geographie.Commune;
import fr.factory.tif.pcu.musee.ThemeMusee;
import fr.factory.tif.vil.animation.Animation;
import fr.factory.tif.generic.telecom.TypeTelecom;
import fr.factory.tif.pcu.sitemonument.CategorieSite;
import fr.factory.dao.interfaces.BifaceI18n;
import fr.factory.tif.vil.labelclassement.LabelClassement;
import fr.factory.tif.hlo.SubTypeHabitation;
import fr.factory.tif.iti.TypeThematique;
import fr.factory.tif.generic.tarifs.Charge;
import fr.factory.tif.pcu.PatrimoineCulturel;
import fr.factory.tif.pcu.musee.CategorieMusee;
import fr.factory.tif.generic.espace.TypeDescription;
import fr.factory.tif.generic.capacite.TypeCapacite;
import fr.factory.tif.generic.temps.Saison;
import fr.factory.tif.pcu.sitemonument.ThemeSite;
import fr.factory.tif.generic.confort.Confort;
import fr.factory.tif.loi.Loisirs;
import fr.factory.tif.generic.reservation.TypeReservation;
import fr.factory.tif.hlo.HebergementLocatif;
import fr.factory.tif.generic.chaine.Chaine;
import fr.factory.tif.generic.service.Service;
import java.util.*;
import fr.factory.tif.hpa.HotelleriePleinAir;
import fr.factory.tif.generic.confort.TypeConfort;
import fr.factory.tif.deg.StatutExploitant;
import fr.factory.tif.generic.activite.Activite;
import fr.factory.tif.generic.visite.TypeVisite;
import fr.factory.tif.ota.Description;
import fr.factory.tif.generic.geographie.ZoneLocale;
import fr.factory.tif.generic.acces.localacces.TypeLocalAcces;
import fr.factory.tif.generic.labelclassement.Classement;
import java.util.Date;
import fr.factory.tif.generic.utils.Mesure;
import fr.factory.tif.res.DescriptionResto;
import fr.factory.tif.deg.VisiteDegustation;
import fr.factory.tif.pcu.parcjardin.ParcJardin;
import fr.factory.tif.generic.equipement.TypeEquipement;
import fr.factory.tif.generic.geographie.Microregion;
import java.util.Locale;
import fr.factory.tif.res.Specialite;
import fr.factory.tif.loi.TypeLoisirs;
import fr.factory.tif.generic.contact.TypeContact;
import fr.factory.tif.pcu.centre.CentreInterpretation;
import fr.factory.tif.generic.capacite.Capacite;
import java.lang.reflect.Method;
import fr.factory.tif.vil.labelclassement.ClassementEnvironement;
import fr.factory.tif.iti.Thematique;
import fr.factory.tif.vil.TypeGestion;
import fr.factory.tif.fma.ThemeFeteManifestation;
import fr.factory.tif.generic.geographie.Adresse;
import fr.factory.tif.generic.categorie.TypeCategorie;
import fr.factory.tif.generic.personne.Personne;
import fr.factory.tif.pcu.centre.ThemeCentreInterpretation;

import fr.factory.tif.mul.TypeMime;
import fr.factory.tif.generic.temps.PeriodeTemporelle;
import fr.factory.tif.vil.labelclassement.ClassementLoisirService;
import fr.factory.tif.ota.ObjetTouristiqueAbstrait;
import fr.factory.tif.pcu.sitemonument.StyleSite;
import fr.factory.tif.res.Restauration;
import java.util.HashMap;
import fr.factory.tif.generic.acces.localacces.LocalAcces;
import fr.factory.tif.ota.TypeObjetTouristique;
import fr.factory.tif.generic.activite.TypeActivite;
import fr.factory.tif.ascf.SportCultFormule;
import fr.factory.tif.fma.Evenement;
import fr.factory.tif.generic.tarifs.TypeCharge;
import fr.factory.tif.vil.animation.ThemeAnimation;
import fr.factory.tif.mul.TypeMultimedia;
import fr.factory.tif.vil.TypeHebergement;
import fr.factory.tif.generic.contact.Contact;
import fr.factory.tif.pna.PatrimoineNaturel;
import fr.factory.tif.vil.TypeBatiment;
import fr.factory.tif.generic.paiement.TypePaiement;
import fr.factory.tif.generic.reservation.Reservation;

import fr.factory.tif.fma.FeteManifestation;
import fr.factory.tif.generic.espace.TypeEspace;
import fr.factory.tif.generic.groupe.TypeGroupe;
import fr.factory.tif.generic.acces.pointacces.TypePointAcces;
import fr.factory.tif.generic.typeobjet.TypeObjet;
import fr.factory.dao.interfaces.Biface;
import fr.factory.tif.generic.groupe.Groupe;
import fr.factory.tif.vil.labelclassement.ClassementPrefectoral;
import fr.factory.tif.application.TypeUtilisateur;
import fr.factory.tif.ascf.TypeSportCultFormule;
import fr.factory.tif.generic.geographie.Canton;
import fr.factory.tif.generic.utils.TourHand;
import fr.factory.tif.mul.Multimedia;
import fr.factory.tif.generic.espace.DescriptionEspace;
import fr.factory.tif.hot.Hotellerie;
import fr.factory.tif.ota.TypePrestation;
import fr.factory.tif.ascf.PrestationProposee;
import fr.factory.tif.deg.Degustation;
import fr.factory.tif.org.ClassementOTSI;

/**
 *  
 * 
 *  Accueil contains all accueil informations, corresponding to the
 * table OUVAC_INFO
 * 
 * @fdao.class table ACCUEIL
 * 
 * .
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class Accueil
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     *  Object's internal ID, corresponding to the field ID_OUVAC
     * of the table.
     * 
     * @fdao.id column ID_ACCUEIL
     * 
     * .
     */
    private Long id;

    /**
     * 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.accueil.OuvertureAccueil
     * 
     *                  table ACCUEIL_OUVERTURE
     * 
     *  
     * 
     * .
     */
    private Vector ouverture;

    /**
     * 
     * 
     * @fdao.property column OUVE24
     * 
     *  
     * 
     * .
     */
    private boolean ouverture24 = false;

    /**
     * 
     * 
     * @fdao.property column VEILNUIT
     * 
     * .
     */
    private boolean veilleurNuit = false;

    /**
     * 
     * 
     * @fdao.property column MOBILITE
     * 
     *  
     * 
     * .
     */
    private boolean personneMobiliteReduite = false;

    /**
     *  Accessibility of animal, corresponding to field ANIMAUX of
     * the table OTA
     * 
     * @fdao.property column ANIMAUX
     * 
     * .
     */
    private boolean acceptAnimal = false;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.generic.utils.Langue
     * 
     *                  table ACCUEIL_ECRIT
     * 
     *                  preferredSize 5
     * 
     *  
     * 
     * .
     */
    private Vector langueEcrite;

    /**
     * 
     * 
     * @fdao.component class fr.factory.tif.generic.utils.Langue
     * 
     *                  table ACCUEIL_PARLE
     * 
     *                  preferredSize 5
     * 
     * .
     */
    private Vector langueParlee;

    /**
     *  Complement Informations of the Accueil, corresponding to
     * the field CUEILCOMPL of the table
     * 
     * @fdao.property column CUEILCOMPL
     * 
     *                  i18n true
     * 
     *                  size 80
     * 
     * @tif.property  size 80
     * 
     * .
     */
    private String[] complement;

      public Long getId() {
  /* {null=Long
}*/

		return id;
  }

      public void setId(Long long1) {
  /* {null=void
}*/

		id= long1;
  }

      public String[] getComplement() {
		return complement;
  }

      public void setComplement(String[] strings) {
  /* {param=strings
}*/

		complement = strings;
  }

      public boolean isPersonneMobiliteReduite() {
  /* {return

	=* @return boolean
}*/

		return personneMobiliteReduite;
  }

      public void setPersonneMobiliteReduite(boolean b) {
  /* {param=b

, null=void
}*/

		personneMobiliteReduite = b;
  }

      public Vector getLangueEcrite() {
  /* {return

	=* @return Vector
}*/

		return langueEcrite;
  }

      public Vector getLangueParlee() {
  /* {return

	=* @return Vector
}*/

		return langueParlee;
  }

      public void setLangueEcrite(Vector vector) {
  /* {param=vector

, null=void
}*/

		langueEcrite = vector;
  }

      public void setLangueParlee(Vector vector) {
  /* {param=vector

, null=void
}*/

		langueParlee = vector;
  }

      public boolean isAcceptAnimal() {
  /* {return

	=* @return boolean
}*/

		return acceptAnimal;
  }

      public void setAcceptAnimal(boolean b) {
  /* {param=b

, null=void
}*/

		acceptAnimal = b;
  }

      public boolean isOuverture24() {
  /* {return

	=* @return boolean
}*/

		return ouverture24;
  }

      public void setOuverture24(boolean b) {
  /* {param=b

, null=void
}*/

		ouverture24 = b;
  }

      public boolean isVeilleurNuit() {
  /* {return

	=* @return boolean
}*/

		return veilleurNuit;
  }

      public void setVeilleurNuit(boolean b) {
  /* {param=b

, null=void
}*/

		veilleurNuit = b;
  }

      public Vector getOuverture() {
  /* {return

	=* @return Vector
}*/

		return ouverture;
  }

      public void setOuverture(Vector vector) {
  /* {param=vector

, null=void
}*/

		ouverture = vector;
  }

}
