/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.3-FRVNS on 2014-10-28 21:59:14,
 any modifications will be overwritten.
 ==============================================================
 */

package fr.factory.tif.hpa;

  //---------------------------------/
 //- Imported classes and packages -/
//---------------------------------/

import fr.factory.tif.res.ClassementGuide;
import fr.factory.tif.generic.confort.CategorieConfort;
import fr.factory.tif.generic.geographie.Pays;
import fr.factory.tif.pcu.parcjardin.ThemeParcJardin;
import fr.factory.tif.generic.acces.pointacces.PointAcces;
import fr.factory.tif.pcu.parcjardin.CategorieParcJardin;
import fr.factory.tif.generic.telecom.AccesTelecom;
import fr.factory.tif.vil.VillageVacance;
import fr.factory.tif.ascf.ActiviteSCF;
import fr.factory.tif.generic.tarifs.TypeTarifs;
import fr.factory.tif.org.SubTypeStructure;
import fr.factory.tif.hlo.labelclassement.Theme;
import java.util.Vector;
import fr.factory.tif.hlo.TypeHabitation;
import fr.factory.tif.iti.Itineraire;
import fr.factory.tif.vil.labelclassement.ClassementConfortSanitaire;
import fr.factory.tif.vil.animation.Disponibilite;
import fr.factory.tif.pcu.parcjardin.StyleParcJardin;
import fr.factory.tif.generic.personne.Civilite;
import fr.factory.tif.generic.equipement.Equipement;
import fr.factory.tif.generic.visite.Visite;
import fr.factory.tif.org.Organisme;
import fr.factory.tif.pcu.musee.Musee;
import fr.factory.tif.hlo.DescriptifHabitation;
import fr.factory.tif.generic.temps.Jour;
import java.io.Serializable;
import fr.factory.tif.pcu.sitemonument.SiteMonumentHistorique;
import fr.factory.tif.generic.geographie.Departement;
import fr.factory.tif.generic.service.TypeService;
import fr.factory.tif.generic.geographie.Region;
import fr.factory.tif.vil.SalleReunion;

import fr.factory.tif.application.Utilisateur;
import fr.factory.tif.ota.Prestation;
import fr.factory.tif.generic.labelclassement.Label;
import fr.factory.tif.vil.TypeClient;
import fr.factory.tif.generic.accueil.Accueil;
import fr.factory.tif.vil.Agrement;
import fr.factory.tif.generic.tarifs.Tarifs;
import fr.factory.tif.generic.utils.Langue;
import fr.factory.tif.generic.espace.Espace;
import fr.factory.tif.generic.geographie.Commune;
import fr.factory.tif.pcu.musee.ThemeMusee;
import fr.factory.tif.vil.animation.Animation;
import fr.factory.tif.generic.telecom.TypeTelecom;
import fr.factory.tif.pcu.sitemonument.CategorieSite;
import fr.factory.dao.interfaces.BifaceI18n;
import fr.factory.tif.vil.labelclassement.LabelClassement;
import fr.factory.tif.hlo.SubTypeHabitation;
import fr.factory.tif.iti.TypeThematique;
import fr.factory.tif.generic.tarifs.Charge;
import fr.factory.tif.pcu.PatrimoineCulturel;
import fr.factory.tif.pcu.musee.CategorieMusee;
import fr.factory.tif.generic.espace.TypeDescription;
import fr.factory.tif.generic.capacite.TypeCapacite;
import fr.factory.tif.generic.accueil.Horaire;
import fr.factory.tif.generic.temps.Saison;
import fr.factory.tif.pcu.sitemonument.ThemeSite;
import fr.factory.tif.generic.confort.Confort;
import fr.factory.tif.loi.Loisirs;
import fr.factory.tif.generic.reservation.TypeReservation;
import fr.factory.tif.hlo.HebergementLocatif;
import fr.factory.tif.generic.chaine.Chaine;
import fr.factory.tif.generic.service.Service;
import java.util.*;
import fr.factory.tif.generic.confort.TypeConfort;
import fr.factory.tif.deg.StatutExploitant;
import fr.factory.tif.generic.activite.Activite;
import fr.factory.tif.generic.visite.TypeVisite;
import fr.factory.tif.ota.Description;
import fr.factory.tif.generic.geographie.ZoneLocale;
import fr.factory.tif.generic.acces.localacces.TypeLocalAcces;
import fr.factory.tif.generic.labelclassement.Classement;
import java.util.Date;
import fr.factory.tif.generic.utils.Mesure;
import fr.factory.tif.res.DescriptionResto;
import fr.factory.tif.deg.VisiteDegustation;
import fr.factory.tif.pcu.parcjardin.ParcJardin;
import fr.factory.tif.generic.equipement.TypeEquipement;
import fr.factory.tif.generic.geographie.Microregion;
import java.util.Locale;
import fr.factory.tif.res.Specialite;
import fr.factory.tif.loi.TypeLoisirs;
import fr.factory.tif.generic.contact.TypeContact;
import fr.factory.tif.pcu.centre.CentreInterpretation;
import fr.factory.tif.generic.capacite.Capacite;
import java.lang.reflect.Method;
import fr.factory.tif.vil.labelclassement.ClassementEnvironement;
import fr.factory.tif.iti.Thematique;
import fr.factory.tif.vil.TypeGestion;
import fr.factory.tif.fma.ThemeFeteManifestation;
import fr.factory.tif.generic.geographie.Adresse;
import fr.factory.tif.generic.categorie.TypeCategorie;
import fr.factory.tif.generic.personne.Personne;
import fr.factory.tif.pcu.centre.ThemeCentreInterpretation;

import fr.factory.tif.mul.TypeMime;
import fr.factory.tif.generic.temps.PeriodeTemporelle;
import fr.factory.tif.vil.labelclassement.ClassementLoisirService;
import fr.factory.tif.ota.ObjetTouristiqueAbstrait;
import fr.factory.tif.pcu.sitemonument.StyleSite;
import fr.factory.tif.res.Restauration;
import java.util.HashMap;
import fr.factory.tif.generic.acces.localacces.LocalAcces;
import fr.factory.tif.ota.TypeObjetTouristique;
import fr.factory.tif.generic.activite.TypeActivite;
import fr.factory.tif.ascf.SportCultFormule;
import fr.factory.tif.fma.Evenement;
import fr.factory.tif.generic.tarifs.TypeCharge;
import fr.factory.tif.vil.animation.ThemeAnimation;
import fr.factory.tif.mul.TypeMultimedia;
import fr.factory.tif.vil.TypeHebergement;
import fr.factory.tif.generic.contact.Contact;
import fr.factory.tif.pna.PatrimoineNaturel;
import fr.factory.tif.vil.TypeBatiment;
import fr.factory.tif.generic.paiement.TypePaiement;
import fr.factory.tif.generic.reservation.Reservation;

import fr.factory.tif.fma.FeteManifestation;
import fr.factory.tif.generic.espace.TypeEspace;
import fr.factory.tif.generic.groupe.TypeGroupe;
import fr.factory.tif.generic.acces.pointacces.TypePointAcces;
import fr.factory.tif.generic.typeobjet.TypeObjet;
import fr.factory.tif.generic.accueil.OuvertureAccueil;
import fr.factory.dao.interfaces.Biface;
import fr.factory.tif.generic.groupe.Groupe;
import fr.factory.tif.vil.labelclassement.ClassementPrefectoral;
import fr.factory.tif.application.TypeUtilisateur;
import fr.factory.tif.ascf.TypeSportCultFormule;
import fr.factory.tif.generic.geographie.Canton;
import fr.factory.tif.generic.utils.TourHand;
import fr.factory.tif.mul.Multimedia;
import fr.factory.tif.generic.espace.DescriptionEspace;
import fr.factory.tif.hot.Hotellerie;
import fr.factory.tif.ota.TypePrestation;
import fr.factory.tif.ascf.PrestationProposee;
import fr.factory.tif.deg.Degustation;
import fr.factory.tif.org.ClassementOTSI;

/**
 * 
 * 
 * @author viet
 * 
 * 
 * 
 *  The entity Hotellerie de Plein Air de TIF v.2.2
 * 
 * @fdao.class table HPA
 * 
 * @fda.subclass type fr.factory.tif.ota.ObjetTouristiqueAbstrait
 * 
 * .
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class HotelleriePleinAir
    extends ObjetTouristiqueAbstrait
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * 
     * 
     *  Property :  Labels
     * 
     * @fdao.property column LABEL
     * 
     *                 size   80
     * 
     * .
     */
    private String label;

    /**
     * 
     * 
     *  Property : Superficie
     * 
     * @fdao.property column SURFACE
     * 
     *                 size 4
     * 
     * .
     */
    private float superficie = 0.0f;

    /**
     * 
     * 
     *  Property :
     * 
     * @fdao.property column EMPCLASS
     * 
     *                  size 4
     * 
     *   
     * 
     * .
     */
    private long nombreClasses = 0L;

    /**
     * 
     * 
     *  Property :
     * 
     * @fdao.property column EMPTOUR
     * 
     *                  size 4
     * 
     * .
     */
    private long nombreTourisme = 0L;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.property column EMPLOIS
     * 
     *                  size 4
     * 
     * .
     */
    private long nombreLoisirs = 0L;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.property column CARAVANEIG
     * 
     * .
     */
    private boolean caravaneige = false;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.property column NATURISME
     * 
     * .
     */
    private boolean naturisme = false;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.property column CAPTOT
     * 
     *                  size 5
     * 
     * .
     */
    private long capaciteGlobaleClassee = 0L;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.property column OMBRE
     * 
     * .
     */
    private boolean ombrage = false;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.property column SEMIOMB
     * 
     * .
     */
    private boolean semiOmbrage = false;

    /**
     * 
     * 
     *  Est-ce que le produit est un adherent syndicat?
     * 
     * @fdao.property column ADHERENTSYN
     * 
     * .
     */
    private boolean adherentSyndicat = false;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.categorie.TypeCategorie
     * 
     * .
     */
    private TypeCategorie categorie;

    /**
     * 
     * 
     *  Property : TypeObjet
     * 
     * @fdao.component class
     * fr.factory.tif.generic.typeobjet.TypeObjet
     * 
     * .
     */
    private TypeObjet typeObjet;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.component class fr.factory.tif.generic.utils.TourHand
     * 
     * .
     */
    private TourHand tourHand;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.component class fr.factory.tif.hpa.TypeGestion
     * 
     * .
     */
    private TypeGestion modeGestion;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.component class fr.factory.tif.generic.chaine.Chaine
     * 
     *                  table OTA_CHAINE
     * 
     * .
     */
    private Vector chaine;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.equipement.Equipement
     * 
     *                  table OTA_EQUIP
     * 
     * .
     */
    private Vector equipement;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.component class fr.factory.tif.generic.service.Service
     * 
     *                  table OTA_SERVICE
     * 
     * .
     */
    private Vector service;

    /**
     * 
     * 
     *  Property : 
     * 
     * @fdao.component class
     * fr.factory.tif.generic.activite.Activite
     * 
     *                  table OTA_ACTIVITE
     * 
     * .
     */
    private Vector activite;

      public Vector getActivite() {
		return activite;
  }

      public long getCapaciteGlobaleClassee() {
		return capaciteGlobaleClassee;
  }

      public boolean isCaravaneige() {
		return caravaneige;
  }

      public TypeCategorie getCategorie() {
		return categorie;
  }

      public Vector getChaine() {
		return chaine;
  }

      public Vector getEquipement() {
		return equipement;
  }

      public String getLabel() {
		return label;
  }

      public boolean isNaturisme() {
		return naturisme;
  }

      public long getNombreClasses() {
		return nombreClasses;
  }

      public long getNombreLoisirs() {
		return nombreLoisirs;
  }

      public long getNombreTourisme() {
		return nombreTourisme;
  }

      public boolean isOmbrage() {
		return ombrage;
  }

      public boolean isSemiOmbrage() {
		return semiOmbrage;
  }

      public Vector getService() {
		return service;
  }

      public float getSuperficie() {
		return superficie;
  }

      public TourHand getTourHand() {
		return tourHand;
  }

      public TypeObjet getTypeObjet() {
		return typeObjet;
  }

      public void setActivite(Vector vector) {
  /* {param=vector
}*/

		activite = vector;
  }

      public void setCapaciteGlobaleClassee(long l) {
  /* {param=l
}*/

		capaciteGlobaleClassee = l;
  }

      public void setCaravaneige(boolean b) {
  /* {param=b
}*/

		caravaneige = b;
  }

      public void setCategorie(TypeCategorie categorie) {
  /* {param=categorie
}*/

		this.categorie = categorie;
  }

      public void setChaine(Vector vector) {
  /* {param=vector
}*/

		chaine = vector;
  }

      public void setEquipement(Vector vector) {
  /* {param=vector
}*/

		equipement = vector;
  }

      public void setLabel(String string) {
  /* {param=string
}*/

		label = string;
  }

      public void setNaturisme(boolean b) {
  /* {param=b
}*/

		naturisme = b;
  }

      public void setNombreClasses(long l) {
  /* {param=l
}*/

		nombreClasses = l;
  }

      public void setNombreLoisirs(long l) {
  /* {param=l
}*/

		nombreLoisirs = l;
  }

      public void setNombreTourisme(long l) {
  /* {param=l
}*/

		nombreTourisme = l;
  }

      public void setOmbrage(boolean b) {
  /* {param=b
}*/

		ombrage = b;
  }

      public void setSemiOmbrage(boolean b) {
  /* {param=b
}*/

		semiOmbrage = b;
  }

      public void setService(Vector vector) {
  /* {param=vector
}*/

		service = vector;
  }

      public void setSuperficie(float f) {
  /* {param=f
}*/

		superficie = f;
  }

      public void setTourHand(TourHand hand) {
  /* {param=hand
}*/

		tourHand = hand;
  }

      public void setTypeObjet(TypeObjet objet) {
  /* {param=objet
}*/

		typeObjet = objet;
  }

      public TypeGestion getModeGestion() {
  /* {return

	=* @return TypeGestion
}*/

		return modeGestion;
  }

      public void setModeGestion(TypeGestion gestion) {
  /* {param=gestion

, null=void
}*/

		modeGestion = gestion;
  }

      public boolean isAdherentSyndicat() {
  /* {return

	=* @return boolean
}*/

		return adherentSyndicat;
  }

      public void setAdherentSyndicat(boolean b) {
  /* {param=b

, null=void
}*/

		adherentSyndicat = b;
  }

}
